/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.records;


import cn.yxtreme.jooq.jooq.tables.Arrangement;
import cn.yxtreme.jooq.jooq.tables.pojos.ArrangementPO;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 开药表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArrangementRecord extends UpdatableRecordImpl<ArrangementRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.arrangement.id</code>. 主键id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.arrangement.id</code>. 主键id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.arrangement.order_id</code>. 订单id
     */
    public void setOrderId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.arrangement.order_id</code>. 订单id
     */
    public Long getOrderId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.arrangement.data</code>. 数据json结构体
     */
    public void setData(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.arrangement.data</code>. 数据json结构体
     */
    public String getData() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.arrangement.created_user</code>. 创建人
     */
    public void setCreatedUser(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.arrangement.created_user</code>. 创建人
     */
    public Long getCreatedUser() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.arrangement.updated_user</code>. 更新人
     */
    public void setUpdatedUser(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.arrangement.updated_user</code>. 更新人
     */
    public Long getUpdatedUser() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.arrangement.created_time</code>. 创建时间
     */
    public void setCreatedTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.arrangement.created_time</code>. 创建时间
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.arrangement.updated_time</code>. 更新时间
     */
    public void setUpdatedTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.arrangement.updated_time</code>. 更新时间
     */
    public LocalDateTime getUpdatedTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.arrangement.car_status</code>. 加车状态
     */
    public void setCarStatus(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.arrangement.car_status</code>. 加车状态
     */
    public Integer getCarStatus() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.arrangement.patient_id</code>. 患者id
     */
    public void setPatientId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.arrangement.patient_id</code>. 患者id
     */
    public Long getPatientId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.arrangement.provider_id</code>. 医生组长id
     */
    public void setProviderId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.arrangement.provider_id</code>. 医生组长id
     */
    public Long getProviderId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.arrangement.user_id</code>. 助手id
     */
    public void setUserId(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.arrangement.user_id</code>. 助手id
     */
    public Long getUserId() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.arrangement.session_id</code>. 会话id
     */
    public void setSessionId(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.arrangement.session_id</code>. 会话id
     */
    public Long getSessionId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.arrangement.leader_id</code>. 组长id
     */
    public void setLeaderId(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.arrangement.leader_id</code>. 组长id
     */
    public Long getLeaderId() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.arrangement.ca_open_id</code>. 对应ca_openid
     */
    public void setCaOpenId(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.arrangement.ca_open_id</code>. 对应ca_openid
     */
    public String getCaOpenId() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.arrangement.pt_no</code>. 就诊人姓名
     */
    public void setPtNo(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.arrangement.pt_no</code>. 就诊人姓名
     */
    public String getPtNo() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.arrangement.birthday</code>. 生日日期 1983-01-20
     */
    public void setBirthday(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.arrangement.birthday</code>. 生日日期 1983-01-20
     */
    public String getBirthday() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.arrangement.sex</code>. 性别 0:男 1:女
     */
    public void setSex(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.arrangement.sex</code>. 性别 0:男 1:女
     */
    public Integer getSex() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>public.arrangement.department_name</code>. 科室名
     */
    public void setDepartmentName(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.arrangement.department_name</code>. 科室名
     */
    public String getDepartmentName() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.arrangement.doctor_name</code>. 医生名
     */
    public void setDoctorName(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.arrangement.doctor_name</code>. 医生名
     */
    public String getDoctorName() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.arrangement.city_name</code>. 患者所在城市
     */
    public void setCityName(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.arrangement.city_name</code>. 患者所在城市
     */
    public String getCityName() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.arrangement.id_no</code>. 患者身份证号
     */
    public void setIdNo(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.arrangement.id_no</code>. 患者身份证号
     */
    public String getIdNo() {
        return (String) get(20);
    }

    /**
     * Setter for <code>public.arrangement.complaint_content</code>. 症状描述
     */
    public void setComplaintContent(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.arrangement.complaint_content</code>. 症状描述
     */
    public String getComplaintContent() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.arrangement.diseaes_name</code>. 疾病
     */
    public void setDiseaesName(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.arrangement.diseaes_name</code>. 疾病
     */
    public String getDiseaesName() {
        return (String) get(22);
    }

    /**
     * Setter for <code>public.arrangement.shop_id</code>. 对应搜索店铺中的商店id
     */
    public void setShopId(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.arrangement.shop_id</code>. 对应搜索店铺中的商店id
     */
    public Integer getShopId() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>public.arrangement.pregnant</code>. 是否孕育 传字符串即可
     */
    public void setPregnant(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.arrangement.pregnant</code>. 是否孕育 传字符串即可
     */
    public String getPregnant() {
        return (String) get(24);
    }

    /**
     * Setter for <code>public.arrangement.allergies</code>. 过敏史
     */
    public void setAllergies(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.arrangement.allergies</code>. 过敏史
     */
    public String getAllergies() {
        return (String) get(25);
    }

    /**
     * Setter for <code>public.arrangement.contraindications</code>. 用药禁忌
     */
    public void setContraindications(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.arrangement.contraindications</code>. 用药禁忌
     */
    public String getContraindications() {
        return (String) get(26);
    }

    /**
     * Setter for <code>public.arrangement.weight</code>. 体重 单位kg
     */
    public void setWeight(BigDecimal value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.arrangement.weight</code>. 体重 单位kg
     */
    public BigDecimal getWeight() {
        return (BigDecimal) get(27);
    }

    /**
     * Setter for <code>public.arrangement.sum_price</code>. 总价 单位分
     */
    public void setSumPrice(Long value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.arrangement.sum_price</code>. 总价 单位分
     */
    public Long getSumPrice() {
        return (Long) get(28);
    }

    /**
     * Setter for <code>public.arrangement.pdf_base64</code>. pdf 信息
     */
    public void setPdfBase64(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>public.arrangement.pdf_base64</code>. pdf 信息
     */
    public String getPdfBase64() {
        return (String) get(29);
    }

    /**
     * Setter for <code>public.arrangement.ca_unique_id</code>. ca 唯一键
     */
    public void setCaUniqueId(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>public.arrangement.ca_unique_id</code>. ca 唯一键
     */
    public String getCaUniqueId() {
        return (String) get(30);
    }

    /**
     * Setter for <code>public.arrangement.ca_ur_id</code>. ca流水号
     */
    public void setCaUrId(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>public.arrangement.ca_ur_id</code>. ca流水号
     */
    public String getCaUrId() {
        return (String) get(31);
    }

    /**
     * Setter for <code>public.arrangement.prescription_order_id</code>.
     * 处方的订单表中的id
     */
    public void setPrescriptionOrderId(Long value) {
        set(32, value);
    }

    /**
     * Getter for <code>public.arrangement.prescription_order_id</code>.
     * 处方的订单表中的id
     */
    public Long getPrescriptionOrderId() {
        return (Long) get(32);
    }

    /**
     * Setter for <code>public.arrangement.mobile</code>. 患者手机号
     */
    public void setMobile(Long value) {
        set(33, value);
    }

    /**
     * Getter for <code>public.arrangement.mobile</code>. 患者手机号
     */
    public Long getMobile() {
        return (Long) get(33);
    }

    /**
     * Setter for <code>public.arrangement.jpg_base64</code>. jpg的base64
     */
    public void setJpgBase64(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>public.arrangement.jpg_base64</code>. jpg的base64
     */
    public String getJpgBase64() {
        return (String) get(34);
    }

    /**
     * Setter for <code>public.arrangement.sign_base64</code>.
     */
    public void setSignBase64(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>public.arrangement.sign_base64</code>.
     */
    public String getSignBase64() {
        return (String) get(35);
    }

    /**
     * Setter for <code>public.arrangement.is_usable</code>. 是否可用药无忧权益
     */
    public void setIsUsable(Boolean value) {
        set(36, value);
    }

    /**
     * Getter for <code>public.arrangement.is_usable</code>. 是否可用药无忧权益
     */
    public Boolean getIsUsable() {
        return (Boolean) get(36);
    }

    /**
     * Setter for <code>public.arrangement.id_card_type</code>. 证件类型
     * 0 身份证 1护照 4出生证明 6港澳台胞证
     */
    public void setIdCardType(Integer value) {
        set(37, value);
    }

    /**
     * Getter for <code>public.arrangement.id_card_type</code>. 证件类型
     * 0 身份证 1护照 4出生证明 6港澳台胞证
     */
    public Integer getIdCardType() {
        return (Integer) get(37);
    }

    /**
     * Setter for <code>public.arrangement.comments</code>. 医嘱
     */
    public void setComments(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>public.arrangement.comments</code>. 医嘱
     */
    public String getComments() {
        return (String) get(38);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ArrangementRecord
     */
    public ArrangementRecord() {
        super(Arrangement.ARRANGEMENT);
    }

    /**
     * Create a detached, initialised ArrangementRecord
     */
    public ArrangementRecord(Long id, Long orderId, String data, Long createdUser, Long updatedUser, LocalDateTime createdTime, LocalDateTime updatedTime, Integer carStatus, Long patientId, Long providerId, Long userId, Long sessionId, Long leaderId, String caOpenId, String ptNo, String birthday, Integer sex, String departmentName, String doctorName, String cityName, String idNo, String complaintContent, String diseaesName, Integer shopId, String pregnant, String allergies, String contraindications, BigDecimal weight, Long sumPrice, String pdfBase64, String caUniqueId, String caUrId, Long prescriptionOrderId, Long mobile, String jpgBase64, String signBase64, Boolean isUsable, Integer idCardType, String comments) {
        super(Arrangement.ARRANGEMENT);

        setId(id);
        setOrderId(orderId);
        setData(data);
        setCreatedUser(createdUser);
        setUpdatedUser(updatedUser);
        setCreatedTime(createdTime);
        setUpdatedTime(updatedTime);
        setCarStatus(carStatus);
        setPatientId(patientId);
        setProviderId(providerId);
        setUserId(userId);
        setSessionId(sessionId);
        setLeaderId(leaderId);
        setCaOpenId(caOpenId);
        setPtNo(ptNo);
        setBirthday(birthday);
        setSex(sex);
        setDepartmentName(departmentName);
        setDoctorName(doctorName);
        setCityName(cityName);
        setIdNo(idNo);
        setComplaintContent(complaintContent);
        setDiseaesName(diseaesName);
        setShopId(shopId);
        setPregnant(pregnant);
        setAllergies(allergies);
        setContraindications(contraindications);
        setWeight(weight);
        setSumPrice(sumPrice);
        setPdfBase64(pdfBase64);
        setCaUniqueId(caUniqueId);
        setCaUrId(caUrId);
        setPrescriptionOrderId(prescriptionOrderId);
        setMobile(mobile);
        setJpgBase64(jpgBase64);
        setSignBase64(signBase64);
        setIsUsable(isUsable);
        setIdCardType(idCardType);
        setComments(comments);
    }

    /**
     * Create a detached, initialised ArrangementRecord
     */
    public ArrangementRecord(ArrangementPO value) {
        super(Arrangement.ARRANGEMENT);

        if (value != null) {
            setId(value.getId());
            setOrderId(value.getOrderId());
            setData(value.getData());
            setCreatedUser(value.getCreatedUser());
            setUpdatedUser(value.getUpdatedUser());
            setCreatedTime(value.getCreatedTime());
            setUpdatedTime(value.getUpdatedTime());
            setCarStatus(value.getCarStatus());
            setPatientId(value.getPatientId());
            setProviderId(value.getProviderId());
            setUserId(value.getUserId());
            setSessionId(value.getSessionId());
            setLeaderId(value.getLeaderId());
            setCaOpenId(value.getCaOpenId());
            setPtNo(value.getPtNo());
            setBirthday(value.getBirthday());
            setSex(value.getSex());
            setDepartmentName(value.getDepartmentName());
            setDoctorName(value.getDoctorName());
            setCityName(value.getCityName());
            setIdNo(value.getIdNo());
            setComplaintContent(value.getComplaintContent());
            setDiseaesName(value.getDiseaesName());
            setShopId(value.getShopId());
            setPregnant(value.getPregnant());
            setAllergies(value.getAllergies());
            setContraindications(value.getContraindications());
            setWeight(value.getWeight());
            setSumPrice(value.getSumPrice());
            setPdfBase64(value.getPdfBase64());
            setCaUniqueId(value.getCaUniqueId());
            setCaUrId(value.getCaUrId());
            setPrescriptionOrderId(value.getPrescriptionOrderId());
            setMobile(value.getMobile());
            setJpgBase64(value.getJpgBase64());
            setSignBase64(value.getSignBase64());
            setIsUsable(value.getIsUsable());
            setIdCardType(value.getIdCardType());
            setComments(value.getComments());
        }
    }
}
