/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.records;


import cn.yxtreme.jooq.jooq.tables.ExpressDelivery;
import cn.yxtreme.jooq.jooq.tables.pojos.ExpressDeliveryPO;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExpressDeliveryRecord extends UpdatableRecordImpl<ExpressDeliveryRecord> implements Record8<Long, String, String, LocalDateTime, LocalDateTime, String, JSON, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.express_delivery.id</code>. 主键id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.express_delivery.id</code>. 主键id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.express_delivery.carrier_company</code>. 快递公司
     */
    public void setCarrierCompany(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.express_delivery.carrier_company</code>. 快递公司
     */
    public String getCarrierCompany() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.express_delivery.carrier_orderId</code>. 快递单号 
     */
    public void setCarrierOrderid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.express_delivery.carrier_orderId</code>. 快递单号 
     */
    public String getCarrierOrderid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.express_delivery.created_time</code>. 创建时间
     */
    public void setCreatedTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.express_delivery.created_time</code>. 创建时间
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.express_delivery.updated_time</code>. 更新时间
     */
    public void setUpdatedTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.express_delivery.updated_time</code>. 更新时间
     */
    public LocalDateTime getUpdatedTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.express_delivery.order_id</code>. 订单id
     */
    public void setOrderId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.express_delivery.order_id</code>. 订单id
     */
    public String getOrderId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.express_delivery.deliver_info</code>. 快递信息
     */
    public void setDeliverInfo(JSON value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.express_delivery.deliver_info</code>. 快递信息
     */
    public JSON getDeliverInfo() {
        return (JSON) get(6);
    }

    /**
     * Setter for <code>public.express_delivery.third_business</code>. 渠道编码
     */
    public void setThirdBusiness(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.express_delivery.third_business</code>. 渠道编码
     */
    public Integer getThirdBusiness() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, LocalDateTime, LocalDateTime, String, JSON, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, String, String, LocalDateTime, LocalDateTime, String, JSON, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ExpressDelivery.EXPRESS_DELIVERY.ID;
    }

    @Override
    public Field<String> field2() {
        return ExpressDelivery.EXPRESS_DELIVERY.CARRIER_COMPANY;
    }

    @Override
    public Field<String> field3() {
        return ExpressDelivery.EXPRESS_DELIVERY.CARRIER_ORDERID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return ExpressDelivery.EXPRESS_DELIVERY.CREATED_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return ExpressDelivery.EXPRESS_DELIVERY.UPDATED_TIME;
    }

    @Override
    public Field<String> field6() {
        return ExpressDelivery.EXPRESS_DELIVERY.ORDER_ID;
    }

    @Override
    public Field<JSON> field7() {
        return ExpressDelivery.EXPRESS_DELIVERY.DELIVER_INFO;
    }

    @Override
    public Field<Integer> field8() {
        return ExpressDelivery.EXPRESS_DELIVERY.THIRD_BUSINESS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCarrierCompany();
    }

    @Override
    public String component3() {
        return getCarrierOrderid();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedTime();
    }

    @Override
    public String component6() {
        return getOrderId();
    }

    @Override
    public JSON component7() {
        return getDeliverInfo();
    }

    @Override
    public Integer component8() {
        return getThirdBusiness();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCarrierCompany();
    }

    @Override
    public String value3() {
        return getCarrierOrderid();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedTime();
    }

    @Override
    public String value6() {
        return getOrderId();
    }

    @Override
    public JSON value7() {
        return getDeliverInfo();
    }

    @Override
    public Integer value8() {
        return getThirdBusiness();
    }

    @Override
    public ExpressDeliveryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ExpressDeliveryRecord value2(String value) {
        setCarrierCompany(value);
        return this;
    }

    @Override
    public ExpressDeliveryRecord value3(String value) {
        setCarrierOrderid(value);
        return this;
    }

    @Override
    public ExpressDeliveryRecord value4(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public ExpressDeliveryRecord value5(LocalDateTime value) {
        setUpdatedTime(value);
        return this;
    }

    @Override
    public ExpressDeliveryRecord value6(String value) {
        setOrderId(value);
        return this;
    }

    @Override
    public ExpressDeliveryRecord value7(JSON value) {
        setDeliverInfo(value);
        return this;
    }

    @Override
    public ExpressDeliveryRecord value8(Integer value) {
        setThirdBusiness(value);
        return this;
    }

    @Override
    public ExpressDeliveryRecord values(Long value1, String value2, String value3, LocalDateTime value4, LocalDateTime value5, String value6, JSON value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExpressDeliveryRecord
     */
    public ExpressDeliveryRecord() {
        super(ExpressDelivery.EXPRESS_DELIVERY);
    }

    /**
     * Create a detached, initialised ExpressDeliveryRecord
     */
    public ExpressDeliveryRecord(Long id, String carrierCompany, String carrierOrderid, LocalDateTime createdTime, LocalDateTime updatedTime, String orderId, JSON deliverInfo, Integer thirdBusiness) {
        super(ExpressDelivery.EXPRESS_DELIVERY);

        setId(id);
        setCarrierCompany(carrierCompany);
        setCarrierOrderid(carrierOrderid);
        setCreatedTime(createdTime);
        setUpdatedTime(updatedTime);
        setOrderId(orderId);
        setDeliverInfo(deliverInfo);
        setThirdBusiness(thirdBusiness);
    }

    /**
     * Create a detached, initialised ExpressDeliveryRecord
     */
    public ExpressDeliveryRecord(ExpressDeliveryPO value) {
        super(ExpressDelivery.EXPRESS_DELIVERY);

        if (value != null) {
            setId(value.getId());
            setCarrierCompany(value.getCarrierCompany());
            setCarrierOrderid(value.getCarrierOrderid());
            setCreatedTime(value.getCreatedTime());
            setUpdatedTime(value.getUpdatedTime());
            setOrderId(value.getOrderId());
            setDeliverInfo(value.getDeliverInfo());
            setThirdBusiness(value.getThirdBusiness());
        }
    }
}
