/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.records;


import cn.yxtreme.jooq.jooq.tables.InterfaceRecord;
import cn.yxtreme.jooq.jooq.tables.pojos.InterfaceRecordPO;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 接口调用记录表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InterfaceRecordRecord extends UpdatableRecordImpl<InterfaceRecordRecord> implements Record5<Long, String, String, String, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.interface_record.id</code>. 主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.interface_record.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.interface_record.interface_name</code>. 接口名
     */
    public void setInterfaceName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.interface_record.interface_name</code>. 接口名
     */
    public String getInterfaceName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.interface_record.request</code>. 请求参数
     */
    public void setRequest(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.interface_record.request</code>. 请求参数
     */
    public String getRequest() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.interface_record.response</code>. 返回参数
     */
    public void setResponse(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.interface_record.response</code>. 返回参数
     */
    public String getResponse() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.interface_record.created_at</code>. 创建时间
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.interface_record.created_at</code>. 创建时间
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, String, OffsetDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, String, String, OffsetDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return InterfaceRecord.INTERFACE_RECORD.ID;
    }

    @Override
    public Field<String> field2() {
        return InterfaceRecord.INTERFACE_RECORD.INTERFACE_NAME;
    }

    @Override
    public Field<String> field3() {
        return InterfaceRecord.INTERFACE_RECORD.REQUEST;
    }

    @Override
    public Field<String> field4() {
        return InterfaceRecord.INTERFACE_RECORD.RESPONSE;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return InterfaceRecord.INTERFACE_RECORD.CREATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getInterfaceName();
    }

    @Override
    public String component3() {
        return getRequest();
    }

    @Override
    public String component4() {
        return getResponse();
    }

    @Override
    public OffsetDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getInterfaceName();
    }

    @Override
    public String value3() {
        return getRequest();
    }

    @Override
    public String value4() {
        return getResponse();
    }

    @Override
    public OffsetDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public InterfaceRecordRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public InterfaceRecordRecord value2(String value) {
        setInterfaceName(value);
        return this;
    }

    @Override
    public InterfaceRecordRecord value3(String value) {
        setRequest(value);
        return this;
    }

    @Override
    public InterfaceRecordRecord value4(String value) {
        setResponse(value);
        return this;
    }

    @Override
    public InterfaceRecordRecord value5(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public InterfaceRecordRecord values(Long value1, String value2, String value3, String value4, OffsetDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InterfaceRecordRecord
     */
    public InterfaceRecordRecord() {
        super(InterfaceRecord.INTERFACE_RECORD);
    }

    /**
     * Create a detached, initialised InterfaceRecordRecord
     */
    public InterfaceRecordRecord(Long id, String interfaceName, String request, String response, OffsetDateTime createdAt) {
        super(InterfaceRecord.INTERFACE_RECORD);

        setId(id);
        setInterfaceName(interfaceName);
        setRequest(request);
        setResponse(response);
        setCreatedAt(createdAt);
    }

    /**
     * Create a detached, initialised InterfaceRecordRecord
     */
    public InterfaceRecordRecord(InterfaceRecordPO value) {
        super(InterfaceRecord.INTERFACE_RECORD);

        if (value != null) {
            setId(value.getId());
            setInterfaceName(value.getInterfaceName());
            setRequest(value.getRequest());
            setResponse(value.getResponse());
            setCreatedAt(value.getCreatedAt());
        }
    }
}
