/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.records;


import cn.yxtreme.jooq.jooq.tables.MedicineV2;
import cn.yxtreme.jooq.jooq.tables.pojos.MedicineV2PO;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 开药表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedicineV2Record extends UpdatableRecordImpl<MedicineV2Record> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.medicine_v2.id</code>. 主键id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.medicine_v2.id</code>. 主键id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.medicine_v2.consult_order_id</code>. 订单id
     */
    public void setConsultOrderId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.medicine_v2.consult_order_id</code>. 订单id
     */
    public Long getConsultOrderId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.medicine_v2.created_time</code>. 创建时间
     */
    public void setCreatedTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.medicine_v2.created_time</code>. 创建时间
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.medicine_v2.patient_id</code>. 患者id
     */
    public void setPatientId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.medicine_v2.patient_id</code>. 患者id
     */
    public Long getPatientId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.medicine_v2.provider_id</code>. 医生组长id
     */
    public void setProviderId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.medicine_v2.provider_id</code>. 医生组长id
     */
    public Long getProviderId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.medicine_v2.assistant_id</code>. 助手id
     */
    public void setAssistantId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.medicine_v2.assistant_id</code>. 助手id
     */
    public Long getAssistantId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.medicine_v2.im_session_id</code>. 会话id
     */
    public void setImSessionId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.medicine_v2.im_session_id</code>. 会话id
     */
    public Long getImSessionId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.medicine_v2.leader_id</code>. 组长id
     */
    public void setLeaderId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.medicine_v2.leader_id</code>. 组长id
     */
    public Long getLeaderId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.medicine_v2.pt_no</code>. 就诊人姓名
     */
    public void setPtNo(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.medicine_v2.pt_no</code>. 就诊人姓名
     */
    public String getPtNo() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.medicine_v2.birthday</code>. 生日日期 1983-01-20
     */
    public void setBirthday(LocalDate value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.medicine_v2.birthday</code>. 生日日期 1983-01-20
     */
    public LocalDate getBirthday() {
        return (LocalDate) get(9);
    }

    /**
     * Setter for <code>public.medicine_v2.sex</code>. 性别 0:男 1:女
     */
    public void setSex(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.medicine_v2.sex</code>. 性别 0:男 1:女
     */
    public Integer getSex() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.medicine_v2.department_name</code>. 科室名
     */
    public void setDepartmentName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.medicine_v2.department_name</code>. 科室名
     */
    public String getDepartmentName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.medicine_v2.id_no</code>. 患者身份证号
     */
    public void setIdNo(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.medicine_v2.id_no</code>. 患者身份证号
     */
    public String getIdNo() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.medicine_v2.complaint_content</code>. 症状描述
     */
    public void setComplaintContent(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.medicine_v2.complaint_content</code>. 症状描述
     */
    public String getComplaintContent() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.medicine_v2.diseaes_name</code>. 疾病
     */
    public void setDiseaesName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.medicine_v2.diseaes_name</code>. 疾病
     */
    public String getDiseaesName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.medicine_v2.shop_id</code>. 对应搜索店铺中的商店id
     */
    public void setShopId(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.medicine_v2.shop_id</code>. 对应搜索店铺中的商店id
     */
    public String getShopId() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.medicine_v2.pregnant</code>. 是否孕育 传字符串即可
     */
    public void setPregnant(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.medicine_v2.pregnant</code>. 是否孕育 传字符串即可
     */
    public String getPregnant() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.medicine_v2.allergies</code>. 过敏史
     */
    public void setAllergies(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.medicine_v2.allergies</code>. 过敏史
     */
    public String getAllergies() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.medicine_v2.contraindications</code>. 用药禁忌
     */
    public void setContraindications(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.medicine_v2.contraindications</code>. 用药禁忌
     */
    public String getContraindications() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.medicine_v2.weight</code>. 体重 单位kg
     */
    public void setWeight(BigDecimal value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.medicine_v2.weight</code>. 体重 单位kg
     */
    public BigDecimal getWeight() {
        return (BigDecimal) get(19);
    }

    /**
     * Setter for <code>public.medicine_v2.medicine_order_id</code>. 处方的订单表中的id
     */
    public void setMedicineOrderId(Long value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.medicine_v2.medicine_order_id</code>. 处方的订单表中的id
     */
    public Long getMedicineOrderId() {
        return (Long) get(20);
    }

    /**
     * Setter for <code>public.medicine_v2.is_usable</code>. 是否可用药无忧权益
     */
    public void setIsUsable(Boolean value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.medicine_v2.is_usable</code>. 是否可用药无忧权益
     */
    public Boolean getIsUsable() {
        return (Boolean) get(21);
    }

    /**
     * Setter for <code>public.medicine_v2.id_card_type</code>. 证件类型 0 身份证 1护照
     * 4出生证明 6港澳台胞证
     */
    public void setIdCardType(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.medicine_v2.id_card_type</code>. 证件类型 0 身份证 1护照
     * 4出生证明 6港澳台胞证
     */
    public Integer getIdCardType() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>public.medicine_v2.comments</code>. 医嘱
     */
    public void setComments(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.medicine_v2.comments</code>. 医嘱
     */
    public String getComments() {
        return (String) get(23);
    }

    /**
     * Setter for <code>public.medicine_v2.prescription</code>. 是否处方
     */
    public void setPrescription(Boolean value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.medicine_v2.prescription</code>. 是否处方
     */
    public Boolean getPrescription() {
        return (Boolean) get(24);
    }

    /**
     * Setter for <code>public.medicine_v2.forward</code>. 是否转发
     */
    public void setForward(Boolean value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.medicine_v2.forward</code>. 是否转发
     */
    public Boolean getForward() {
        return (Boolean) get(25);
    }

    /**
     * Setter for <code>public.medicine_v2.forward_user_id</code>. 转发用户id
     */
    public void setForwardUserId(Long value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.medicine_v2.forward_user_id</code>. 转发用户id
     */
    public Long getForwardUserId() {
        return (Long) get(26);
    }

    /**
     * Setter for <code>public.medicine_v2.forward_department</code>. 转发部门
     */
    public void setForwardDepartment(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.medicine_v2.forward_department</code>. 转发部门
     */
    public String getForwardDepartment() {
        return (String) get(27);
    }

    /**
     * Setter for <code>public.medicine_v2.doctor_name</code>. 就诊医生名
     */
    public void setDoctorName(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.medicine_v2.doctor_name</code>. 就诊医生名
     */
    public String getDoctorName() {
        return (String) get(28);
    }

    /**
     * Setter for <code>public.medicine_v2.forward_user_name</code>. 转发人用户名
     */
    public void setForwardUserName(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>public.medicine_v2.forward_user_name</code>. 转发人用户名
     */
    public String getForwardUserName() {
        return (String) get(29);
    }

    /**
     * Setter for <code>public.medicine_v2.prescription_base64</code>. 处方单base64
     */
    public void setPrescriptionBase64(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>public.medicine_v2.prescription_base64</code>. 处方单base64
     */
    public String getPrescriptionBase64() {
        return (String) get(30);
    }

    /**
     * Setter for <code>public.medicine_v2.shop_type</code>. 1:o2o 2:b2c
     */
    public void setShopType(Integer value) {
        set(31, value);
    }

    /**
     * Getter for <code>public.medicine_v2.shop_type</code>. 1:o2o 2:b2c
     */
    public Integer getShopType() {
        return (Integer) get(31);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MedicineV2Record
     */
    public MedicineV2Record() {
        super(MedicineV2.MEDICINE_V2);
    }

    /**
     * Create a detached, initialised MedicineV2Record
     */
    public MedicineV2Record(Long id, Long consultOrderId, LocalDateTime createdTime, Long patientId, Long providerId, Long assistantId, Long imSessionId, Long leaderId, String ptNo, LocalDate birthday, Integer sex, String departmentName, String idNo, String complaintContent, String diseaesName, String shopId, String pregnant, String allergies, String contraindications, BigDecimal weight, Long medicineOrderId, Boolean isUsable, Integer idCardType, String comments, Boolean prescription, Boolean forward, Long forwardUserId, String forwardDepartment, String doctorName, String forwardUserName, String prescriptionBase64, Integer shopType) {
        super(MedicineV2.MEDICINE_V2);

        setId(id);
        setConsultOrderId(consultOrderId);
        setCreatedTime(createdTime);
        setPatientId(patientId);
        setProviderId(providerId);
        setAssistantId(assistantId);
        setImSessionId(imSessionId);
        setLeaderId(leaderId);
        setPtNo(ptNo);
        setBirthday(birthday);
        setSex(sex);
        setDepartmentName(departmentName);
        setIdNo(idNo);
        setComplaintContent(complaintContent);
        setDiseaesName(diseaesName);
        setShopId(shopId);
        setPregnant(pregnant);
        setAllergies(allergies);
        setContraindications(contraindications);
        setWeight(weight);
        setMedicineOrderId(medicineOrderId);
        setIsUsable(isUsable);
        setIdCardType(idCardType);
        setComments(comments);
        setPrescription(prescription);
        setForward(forward);
        setForwardUserId(forwardUserId);
        setForwardDepartment(forwardDepartment);
        setDoctorName(doctorName);
        setForwardUserName(forwardUserName);
        setPrescriptionBase64(prescriptionBase64);
        setShopType(shopType);
    }

    /**
     * Create a detached, initialised MedicineV2Record
     */
    public MedicineV2Record(MedicineV2PO value) {
        super(MedicineV2.MEDICINE_V2);

        if (value != null) {
            setId(value.getId());
            setConsultOrderId(value.getConsultOrderId());
            setCreatedTime(value.getCreatedTime());
            setPatientId(value.getPatientId());
            setProviderId(value.getProviderId());
            setAssistantId(value.getAssistantId());
            setImSessionId(value.getImSessionId());
            setLeaderId(value.getLeaderId());
            setPtNo(value.getPtNo());
            setBirthday(value.getBirthday());
            setSex(value.getSex());
            setDepartmentName(value.getDepartmentName());
            setIdNo(value.getIdNo());
            setComplaintContent(value.getComplaintContent());
            setDiseaesName(value.getDiseaesName());
            setShopId(value.getShopId());
            setPregnant(value.getPregnant());
            setAllergies(value.getAllergies());
            setContraindications(value.getContraindications());
            setWeight(value.getWeight());
            setMedicineOrderId(value.getMedicineOrderId());
            setIsUsable(value.getIsUsable());
            setIdCardType(value.getIdCardType());
            setComments(value.getComments());
            setPrescription(value.getPrescription());
            setForward(value.getForward());
            setForwardUserId(value.getForwardUserId());
            setForwardDepartment(value.getForwardDepartment());
            setDoctorName(value.getDoctorName());
            setForwardUserName(value.getForwardUserName());
            setPrescriptionBase64(value.getPrescriptionBase64());
            setShopType(value.getShopType());
        }
    }
}
