/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.records;


import cn.yxtreme.jooq.jooq.tables.MedicineOrder;
import cn.yxtreme.jooq.jooq.tables.pojos.MedicineOrderPO;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 订单表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedicineOrderRecord extends UpdatableRecordImpl<MedicineOrderRecord> implements Record20<Long, LocalDateTime, LocalDateTime, Integer, String, Integer, Long, Long, Long, Long, BigDecimal, BigDecimal, Boolean, String, Boolean, Long, Long, String, Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.medicine_order.id</code>. 主键id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.medicine_order.id</code>. 主键id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.medicine_order.created_time</code>. 创建时间
     */
    public void setCreatedTime(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.medicine_order.created_time</code>. 创建时间
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.medicine_order.updated_time</code>. 更新时间
     */
    public void setUpdatedTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.medicine_order.updated_time</code>. 更新时间
     */
    public LocalDateTime getUpdatedTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.medicine_order.order_status</code>. 订单状态(1, "已创建"
     * 2, "已支付" 3, "配送中" 4, "妥投" 6, "取消" 7, "退款" 8, "药店配货中")
     */
    public void setOrderStatus(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.medicine_order.order_status</code>. 订单状态(1, "已创建"
     * 2, "已支付" 3, "配送中" 4, "妥投" 6, "取消" 7, "退款" 8, "药店配货中")
     */
    public Integer getOrderStatus() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.medicine_order.third_order_id</code>. 叮当对应的订单号
     */
    public void setThirdOrderId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.medicine_order.third_order_id</code>. 叮当对应的订单号
     */
    public String getThirdOrderId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.medicine_order.third_business</code>. 1:叮当 2: 保忠堂
     * 3:小药药
     */
    public void setThirdBusiness(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.medicine_order.third_business</code>. 1:叮当 2: 保忠堂
     * 3:小药药
     */
    public Integer getThirdBusiness() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.medicine_order.total_price</code>. 商品总金额 单位：分
     */
    public void setTotalPrice(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.medicine_order.total_price</code>. 商品总金额 单位：分
     */
    public Long getTotalPrice() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.medicine_order.deduction_ammount</code>. 保险抵扣金额
     * 单位：分
     */
    public void setDeductionAmmount(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.medicine_order.deduction_ammount</code>. 保险抵扣金额
     * 单位：分
     */
    public Long getDeductionAmmount() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.medicine_order.deliver_pay</code>. 运费单位分
     */
    public void setDeliverPay(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.medicine_order.deliver_pay</code>. 运费单位分
     */
    public Long getDeliverPay() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.medicine_order.had_pay</code>. 实际支付金额
     */
    public void setHadPay(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.medicine_order.had_pay</code>. 实际支付金额
     */
    public Long getHadPay() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.medicine_order.latitude</code>. 纬度
     */
    public void setLatitude(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.medicine_order.latitude</code>. 纬度
     */
    public BigDecimal getLatitude() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>public.medicine_order.longitude</code>. 经度
     */
    public void setLongitude(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.medicine_order.longitude</code>. 经度
     */
    public BigDecimal getLongitude() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>public.medicine_order.rights</code>. 是否使用权益
     */
    public void setRights(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.medicine_order.rights</code>. 是否使用权益
     */
    public Boolean getRights() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>public.medicine_order.rights_use_id</code>. 权益锁定使用的id
     */
    public void setRightsUseId(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.medicine_order.rights_use_id</code>. 权益锁定使用的id
     */
    public String getRightsUseId() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.medicine_order.rights_commit</code>. 权益是否已提交
     */
    public void setRightsCommit(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.medicine_order.rights_commit</code>. 权益是否已提交
     */
    public Boolean getRightsCommit() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>public.medicine_order.rights_id</code>. 权益id
     */
    public void setRightsId(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.medicine_order.rights_id</code>. 权益id
     */
    public Long getRightsId() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>public.medicine_order.deliver_discount</code>. 运费优惠金额
     */
    public void setDeliverDiscount(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.medicine_order.deliver_discount</code>. 运费优惠金额
     */
    public Long getDeliverDiscount() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>public.medicine_order.abandoned_reason</code>. 医生作废原因
     */
    public void setAbandonedReason(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.medicine_order.abandoned_reason</code>. 医生作废原因
     */
    public String getAbandonedReason() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.medicine_order.total_original_price</code>.
     */
    public void setTotalOriginalPrice(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.medicine_order.total_original_price</code>.
     */
    public Long getTotalOriginalPrice() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>public.medicine_order.order_no</code>.
     */
    public void setOrderNo(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.medicine_order.order_no</code>.
     */
    public String getOrderNo() {
        return (String) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row20<Long, LocalDateTime, LocalDateTime, Integer, String, Integer, Long, Long, Long, Long, BigDecimal, BigDecimal, Boolean, String, Boolean, Long, Long, String, Long, String> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    @Override
    public Row20<Long, LocalDateTime, LocalDateTime, Integer, String, Integer, Long, Long, Long, Long, BigDecimal, BigDecimal, Boolean, String, Boolean, Long, Long, String, Long, String> valuesRow() {
        return (Row20) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MedicineOrder.MEDICINE_ORDER.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return MedicineOrder.MEDICINE_ORDER.CREATED_TIME;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return MedicineOrder.MEDICINE_ORDER.UPDATED_TIME;
    }

    @Override
    public Field<Integer> field4() {
        return MedicineOrder.MEDICINE_ORDER.ORDER_STATUS;
    }

    @Override
    public Field<String> field5() {
        return MedicineOrder.MEDICINE_ORDER.THIRD_ORDER_ID;
    }

    @Override
    public Field<Integer> field6() {
        return MedicineOrder.MEDICINE_ORDER.THIRD_BUSINESS;
    }

    @Override
    public Field<Long> field7() {
        return MedicineOrder.MEDICINE_ORDER.TOTAL_PRICE;
    }

    @Override
    public Field<Long> field8() {
        return MedicineOrder.MEDICINE_ORDER.DEDUCTION_AMMOUNT;
    }

    @Override
    public Field<Long> field9() {
        return MedicineOrder.MEDICINE_ORDER.DELIVER_PAY;
    }

    @Override
    public Field<Long> field10() {
        return MedicineOrder.MEDICINE_ORDER.HAD_PAY;
    }

    @Override
    public Field<BigDecimal> field11() {
        return MedicineOrder.MEDICINE_ORDER.LATITUDE;
    }

    @Override
    public Field<BigDecimal> field12() {
        return MedicineOrder.MEDICINE_ORDER.LONGITUDE;
    }

    @Override
    public Field<Boolean> field13() {
        return MedicineOrder.MEDICINE_ORDER.RIGHTS;
    }

    @Override
    public Field<String> field14() {
        return MedicineOrder.MEDICINE_ORDER.RIGHTS_USE_ID;
    }

    @Override
    public Field<Boolean> field15() {
        return MedicineOrder.MEDICINE_ORDER.RIGHTS_COMMIT;
    }

    @Override
    public Field<Long> field16() {
        return MedicineOrder.MEDICINE_ORDER.RIGHTS_ID;
    }

    @Override
    public Field<Long> field17() {
        return MedicineOrder.MEDICINE_ORDER.DELIVER_DISCOUNT;
    }

    @Override
    public Field<String> field18() {
        return MedicineOrder.MEDICINE_ORDER.ABANDONED_REASON;
    }

    @Override
    public Field<Long> field19() {
        return MedicineOrder.MEDICINE_ORDER.TOTAL_ORIGINAL_PRICE;
    }

    @Override
    public Field<String> field20() {
        return MedicineOrder.MEDICINE_ORDER.ORDER_NO;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdatedTime();
    }

    @Override
    public Integer component4() {
        return getOrderStatus();
    }

    @Override
    public String component5() {
        return getThirdOrderId();
    }

    @Override
    public Integer component6() {
        return getThirdBusiness();
    }

    @Override
    public Long component7() {
        return getTotalPrice();
    }

    @Override
    public Long component8() {
        return getDeductionAmmount();
    }

    @Override
    public Long component9() {
        return getDeliverPay();
    }

    @Override
    public Long component10() {
        return getHadPay();
    }

    @Override
    public BigDecimal component11() {
        return getLatitude();
    }

    @Override
    public BigDecimal component12() {
        return getLongitude();
    }

    @Override
    public Boolean component13() {
        return getRights();
    }

    @Override
    public String component14() {
        return getRightsUseId();
    }

    @Override
    public Boolean component15() {
        return getRightsCommit();
    }

    @Override
    public Long component16() {
        return getRightsId();
    }

    @Override
    public Long component17() {
        return getDeliverDiscount();
    }

    @Override
    public String component18() {
        return getAbandonedReason();
    }

    @Override
    public Long component19() {
        return getTotalOriginalPrice();
    }

    @Override
    public String component20() {
        return getOrderNo();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedTime();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdatedTime();
    }

    @Override
    public Integer value4() {
        return getOrderStatus();
    }

    @Override
    public String value5() {
        return getThirdOrderId();
    }

    @Override
    public Integer value6() {
        return getThirdBusiness();
    }

    @Override
    public Long value7() {
        return getTotalPrice();
    }

    @Override
    public Long value8() {
        return getDeductionAmmount();
    }

    @Override
    public Long value9() {
        return getDeliverPay();
    }

    @Override
    public Long value10() {
        return getHadPay();
    }

    @Override
    public BigDecimal value11() {
        return getLatitude();
    }

    @Override
    public BigDecimal value12() {
        return getLongitude();
    }

    @Override
    public Boolean value13() {
        return getRights();
    }

    @Override
    public String value14() {
        return getRightsUseId();
    }

    @Override
    public Boolean value15() {
        return getRightsCommit();
    }

    @Override
    public Long value16() {
        return getRightsId();
    }

    @Override
    public Long value17() {
        return getDeliverDiscount();
    }

    @Override
    public String value18() {
        return getAbandonedReason();
    }

    @Override
    public Long value19() {
        return getTotalOriginalPrice();
    }

    @Override
    public String value20() {
        return getOrderNo();
    }

    @Override
    public MedicineOrderRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value2(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value3(LocalDateTime value) {
        setUpdatedTime(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value4(Integer value) {
        setOrderStatus(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value5(String value) {
        setThirdOrderId(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value6(Integer value) {
        setThirdBusiness(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value7(Long value) {
        setTotalPrice(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value8(Long value) {
        setDeductionAmmount(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value9(Long value) {
        setDeliverPay(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value10(Long value) {
        setHadPay(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value11(BigDecimal value) {
        setLatitude(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value12(BigDecimal value) {
        setLongitude(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value13(Boolean value) {
        setRights(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value14(String value) {
        setRightsUseId(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value15(Boolean value) {
        setRightsCommit(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value16(Long value) {
        setRightsId(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value17(Long value) {
        setDeliverDiscount(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value18(String value) {
        setAbandonedReason(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value19(Long value) {
        setTotalOriginalPrice(value);
        return this;
    }

    @Override
    public MedicineOrderRecord value20(String value) {
        setOrderNo(value);
        return this;
    }

    @Override
    public MedicineOrderRecord values(Long value1, LocalDateTime value2, LocalDateTime value3, Integer value4, String value5, Integer value6, Long value7, Long value8, Long value9, Long value10, BigDecimal value11, BigDecimal value12, Boolean value13, String value14, Boolean value15, Long value16, Long value17, String value18, Long value19, String value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MedicineOrderRecord
     */
    public MedicineOrderRecord() {
        super(MedicineOrder.MEDICINE_ORDER);
    }

    /**
     * Create a detached, initialised MedicineOrderRecord
     */
    public MedicineOrderRecord(Long id, LocalDateTime createdTime, LocalDateTime updatedTime, Integer orderStatus, String thirdOrderId, Integer thirdBusiness, Long totalPrice, Long deductionAmmount, Long deliverPay, Long hadPay, BigDecimal latitude, BigDecimal longitude, Boolean rights, String rightsUseId, Boolean rightsCommit, Long rightsId, Long deliverDiscount, String abandonedReason, Long totalOriginalPrice, String orderNo) {
        super(MedicineOrder.MEDICINE_ORDER);

        setId(id);
        setCreatedTime(createdTime);
        setUpdatedTime(updatedTime);
        setOrderStatus(orderStatus);
        setThirdOrderId(thirdOrderId);
        setThirdBusiness(thirdBusiness);
        setTotalPrice(totalPrice);
        setDeductionAmmount(deductionAmmount);
        setDeliverPay(deliverPay);
        setHadPay(hadPay);
        setLatitude(latitude);
        setLongitude(longitude);
        setRights(rights);
        setRightsUseId(rightsUseId);
        setRightsCommit(rightsCommit);
        setRightsId(rightsId);
        setDeliverDiscount(deliverDiscount);
        setAbandonedReason(abandonedReason);
        setTotalOriginalPrice(totalOriginalPrice);
        setOrderNo(orderNo);
    }

    /**
     * Create a detached, initialised MedicineOrderRecord
     */
    public MedicineOrderRecord(MedicineOrderPO value) {
        super(MedicineOrder.MEDICINE_ORDER);

        if (value != null) {
            setId(value.getId());
            setCreatedTime(value.getCreatedTime());
            setUpdatedTime(value.getUpdatedTime());
            setOrderStatus(value.getOrderStatus());
            setThirdOrderId(value.getThirdOrderId());
            setThirdBusiness(value.getThirdBusiness());
            setTotalPrice(value.getTotalPrice());
            setDeductionAmmount(value.getDeductionAmmount());
            setDeliverPay(value.getDeliverPay());
            setHadPay(value.getHadPay());
            setLatitude(value.getLatitude());
            setLongitude(value.getLongitude());
            setRights(value.getRights());
            setRightsUseId(value.getRightsUseId());
            setRightsCommit(value.getRightsCommit());
            setRightsId(value.getRightsId());
            setDeliverDiscount(value.getDeliverDiscount());
            setAbandonedReason(value.getAbandonedReason());
            setTotalOriginalPrice(value.getTotalOriginalPrice());
            setOrderNo(value.getOrderNo());
        }
    }
}
