/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.records;


import cn.yxtreme.jooq.jooq.tables.NormalMedicationPart;
import cn.yxtreme.jooq.jooq.tables.pojos.NormalMedicationPartPO;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 标准方组成表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NormalMedicationPartRecord extends UpdatableRecordImpl<NormalMedicationPartRecord> implements Record6<Long, BigDecimal, String, Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.normal_medication_part.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.normal_medication_part.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.normal_medication_part.weight</code>. 重量
     */
    public void setWeight(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.normal_medication_part.weight</code>. 重量
     */
    public BigDecimal getWeight() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.normal_medication_part.name</code>. 药名
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.normal_medication_part.name</code>. 药名
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.normal_medication_part.sku_id</code>. sku
     * 表中的sku_id
     */
    public void setSkuId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.normal_medication_part.sku_id</code>. sku
     * 表中的sku_id
     */
    public Long getSkuId() {
        return (Long) get(3);
    }

    /**
     * Setter for
     * <code>public.normal_medication_part.chinese_medicine_id</code>. 药材表中的id
     */
    public void setChineseMedicineId(Long value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.normal_medication_part.chinese_medicine_id</code>. 药材表中的id
     */
    public Long getChineseMedicineId() {
        return (Long) get(4);
    }

    /**
     * Setter for
     * <code>public.normal_medication_part.normal_medication_id</code>. 标准方表中id
     */
    public void setNormalMedicationId(Long value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>public.normal_medication_part.normal_medication_id</code>. 标准方表中id
     */
    public Long getNormalMedicationId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, BigDecimal, String, Long, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, BigDecimal, String, Long, Long, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return NormalMedicationPart.NORMAL_MEDICATION_PART.ID;
    }

    @Override
    public Field<BigDecimal> field2() {
        return NormalMedicationPart.NORMAL_MEDICATION_PART.WEIGHT;
    }

    @Override
    public Field<String> field3() {
        return NormalMedicationPart.NORMAL_MEDICATION_PART.NAME;
    }

    @Override
    public Field<Long> field4() {
        return NormalMedicationPart.NORMAL_MEDICATION_PART.SKU_ID;
    }

    @Override
    public Field<Long> field5() {
        return NormalMedicationPart.NORMAL_MEDICATION_PART.CHINESE_MEDICINE_ID;
    }

    @Override
    public Field<Long> field6() {
        return NormalMedicationPart.NORMAL_MEDICATION_PART.NORMAL_MEDICATION_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public BigDecimal component2() {
        return getWeight();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Long component4() {
        return getSkuId();
    }

    @Override
    public Long component5() {
        return getChineseMedicineId();
    }

    @Override
    public Long component6() {
        return getNormalMedicationId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public BigDecimal value2() {
        return getWeight();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Long value4() {
        return getSkuId();
    }

    @Override
    public Long value5() {
        return getChineseMedicineId();
    }

    @Override
    public Long value6() {
        return getNormalMedicationId();
    }

    @Override
    public NormalMedicationPartRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public NormalMedicationPartRecord value2(BigDecimal value) {
        setWeight(value);
        return this;
    }

    @Override
    public NormalMedicationPartRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public NormalMedicationPartRecord value4(Long value) {
        setSkuId(value);
        return this;
    }

    @Override
    public NormalMedicationPartRecord value5(Long value) {
        setChineseMedicineId(value);
        return this;
    }

    @Override
    public NormalMedicationPartRecord value6(Long value) {
        setNormalMedicationId(value);
        return this;
    }

    @Override
    public NormalMedicationPartRecord values(Long value1, BigDecimal value2, String value3, Long value4, Long value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NormalMedicationPartRecord
     */
    public NormalMedicationPartRecord() {
        super(NormalMedicationPart.NORMAL_MEDICATION_PART);
    }

    /**
     * Create a detached, initialised NormalMedicationPartRecord
     */
    public NormalMedicationPartRecord(Long id, BigDecimal weight, String name, Long skuId, Long chineseMedicineId, Long normalMedicationId) {
        super(NormalMedicationPart.NORMAL_MEDICATION_PART);

        setId(id);
        setWeight(weight);
        setName(name);
        setSkuId(skuId);
        setChineseMedicineId(chineseMedicineId);
        setNormalMedicationId(normalMedicationId);
    }

    /**
     * Create a detached, initialised NormalMedicationPartRecord
     */
    public NormalMedicationPartRecord(NormalMedicationPartPO value) {
        super(NormalMedicationPart.NORMAL_MEDICATION_PART);

        if (value != null) {
            setId(value.getId());
            setWeight(value.getWeight());
            setName(value.getName());
            setSkuId(value.getSkuId());
            setChineseMedicineId(value.getChineseMedicineId());
            setNormalMedicationId(value.getNormalMedicationId());
        }
    }
}
