/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.records;


import cn.yxtreme.jooq.jooq.tables.Order;
import cn.yxtreme.jooq.jooq.tables.pojos.OrderPO;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 订单表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderRecord extends UpdatableRecordImpl<OrderRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.order.id</code>. 主键id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.order.id</code>. 主键id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.order.order_no</code>. 处方订单编号
     */
    public void setOrderNo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.order.order_no</code>. 处方订单编号
     */
    public String getOrderNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.order.created_user</code>. 创建人
     */
    public void setCreatedUser(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.order.created_user</code>. 创建人
     */
    public Long getCreatedUser() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.order.updated_user</code>. 更新人
     */
    public void setUpdatedUser(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.order.updated_user</code>. 更新人
     */
    public Long getUpdatedUser() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.order.created_time</code>. 创建时间
     */
    public void setCreatedTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.order.created_time</code>. 创建时间
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.order.updated_time</code>. 更新时间
     */
    public void setUpdatedTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.order.updated_time</code>. 更新时间
     */
    public LocalDateTime getUpdatedTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.order.order_status</code>. 订单状态(1, "已创建" 2, "已支付"
     * 3, "配送中" 4, "妥投" 6, "取消" 7, "退款" 8, "药店配货中")
     */
    public void setOrderStatus(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.order.order_status</code>. 订单状态(1, "已创建" 2, "已支付"
     * 3, "配送中" 4, "妥投" 6, "取消" 7, "退款" 8, "药店配货中")
     */
    public Integer getOrderStatus() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.order.dd_order_no</code>. 叮当对应的订单号
     */
    public void setDdOrderNo(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.order.dd_order_no</code>. 叮当对应的订单号
     */
    public String getDdOrderNo() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.order.total_price</code>. 商品总金额 单位：分

     */
    public void setTotalPrice(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.order.total_price</code>. 商品总金额 单位：分

     */
    public Long getTotalPrice() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.order.total_pay</code>. 支付金额 单位：分                
     *  = deductionAmount + hadPay = totalPrice + deliverPay 
     */
    public void setTotalPay(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.order.total_pay</code>. 支付金额 单位：分                
     *  = deductionAmount + hadPay = totalPrice + deliverPay 
     */
    public Long getTotalPay() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.order.deduction_ammount</code>. 保险抵扣金额 单位：分
     * 
     * 
     */
    public void setDeductionAmmount(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.order.deduction_ammount</code>. 保险抵扣金额 单位：分
     * 
     * 
     */
    public Long getDeductionAmmount() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.order.deliver_pay</code>. 运费单位分
     */
    public void setDeliverPay(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.order.deliver_pay</code>. 运费单位分
     */
    public Long getDeliverPay() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.order.pay_time</code>. 支付时间
     */
    public void setPayTime(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.order.pay_time</code>. 支付时间
     */
    public LocalDateTime getPayTime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>public.order.init_time</code>. 订单生成时间
     */
    public void setInitTime(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.order.init_time</code>. 订单生成时间
     */
    public LocalDateTime getInitTime() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>public.order.commit_time</code>. 订单提交时间
     */
    public void setCommitTime(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.order.commit_time</code>. 订单提交时间
     */
    public LocalDateTime getCommitTime() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>public.order.cancel_time</code>. 订单取消时间
     */
    public void setCancelTime(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.order.cancel_time</code>. 订单取消时间
     */
    public LocalDateTime getCancelTime() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>public.order.refund_time</code>. 退款时间
     */
    public void setRefundTime(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.order.refund_time</code>. 退款时间
     */
    public LocalDateTime getRefundTime() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>public.order.prescription</code>. 是否处方
     */
    public void setPrescription(Boolean value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.order.prescription</code>. 是否处方
     */
    public Boolean getPrescription() {
        return (Boolean) get(17);
    }

    /**
     * Setter for <code>public.order.had_pay</code>. 现金支付金额 单位：分

     */
    public void setHadPay(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.order.had_pay</code>. 现金支付金额 单位：分

     */
    public Long getHadPay() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>public.order.mobile</code>. 下单人手机号

     */
    public void setMobile(Long value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.order.mobile</code>. 下单人手机号

     */
    public Long getMobile() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>public.order.city</code>. 下单人所在城市

     */
    public void setCity(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.order.city</code>. 下单人所在城市

     */
    public String getCity() {
        return (String) get(20);
    }

    /**
     * Setter for <code>public.order.patient_id</code>. 患者id
     */
    public void setPatientId(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.order.patient_id</code>. 患者id
     */
    public Long getPatientId() {
        return (Long) get(21);
    }

    /**
     * Setter for <code>public.order.leader_id</code>. 组长id
     */
    public void setLeaderId(Long value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.order.leader_id</code>. 组长id
     */
    public Long getLeaderId() {
        return (Long) get(22);
    }

    /**
     * Setter for <code>public.order.provider_id</code>. 助手id
     */
    public void setProviderId(Long value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.order.provider_id</code>. 助手id
     */
    public Long getProviderId() {
        return (Long) get(23);
    }

    /**
     * Setter for <code>public.order.latitude</code>. 纬度
     */
    public void setLatitude(BigDecimal value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.order.latitude</code>. 纬度
     */
    public BigDecimal getLatitude() {
        return (BigDecimal) get(24);
    }

    /**
     * Setter for <code>public.order.longitude</code>. 经度
     */
    public void setLongitude(BigDecimal value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.order.longitude</code>. 经度
     */
    public BigDecimal getLongitude() {
        return (BigDecimal) get(25);
    }

    /**
     * Setter for <code>public.order.address</code>. 具体发货地址
     */
    public void setAddress(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.order.address</code>. 具体发货地址
     */
    public String getAddress() {
        return (String) get(26);
    }

    /**
     * Setter for <code>public.order.right</code>. 是否使用权益
     */
    public void setRight(Boolean value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.order.right</code>. 是否使用权益
     */
    public Boolean getRight() {
        return (Boolean) get(27);
    }

    /**
     * Setter for <code>public.order.doctor_name</code>. 医生姓名
     */
    public void setDoctorName(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.order.doctor_name</code>. 医生姓名
     */
    public String getDoctorName() {
        return (String) get(28);
    }

    /**
     * Setter for <code>public.order.right_use_id</code>. 权益锁定使用的id
     */
    public void setRightUseId(Long value) {
        set(29, value);
    }

    /**
     * Getter for <code>public.order.right_use_id</code>. 权益锁定使用的id
     */
    public Long getRightUseId() {
        return (Long) get(29);
    }

    /**
     * Setter for <code>public.order.delivered_time</code>. 妥投时间
     */
    public void setDeliveredTime(LocalDateTime value) {
        set(30, value);
    }

    /**
     * Getter for <code>public.order.delivered_time</code>. 妥投时间
     */
    public LocalDateTime getDeliveredTime() {
        return (LocalDateTime) get(30);
    }

    /**
     * Setter for <code>public.order.right_commit</code>. 权益是否已提交
     */
    public void setRightCommit(Boolean value) {
        set(31, value);
    }

    /**
     * Getter for <code>public.order.right_commit</code>. 权益是否已提交
     */
    public Boolean getRightCommit() {
        return (Boolean) get(31);
    }

    /**
     * Setter for <code>public.order.rights_id</code>. 权益id
     */
    public void setRightsId(Long value) {
        set(32, value);
    }

    /**
     * Getter for <code>public.order.rights_id</code>. 权益id
     */
    public Long getRightsId() {
        return (Long) get(32);
    }

    /**
     * Setter for <code>public.order.shop_type</code>. 叮当店铺类型 1为o2o2为b2c
     */
    public void setShopType(Integer value) {
        set(33, value);
    }

    /**
     * Getter for <code>public.order.shop_type</code>. 叮当店铺类型 1为o2o2为b2c
     */
    public Integer getShopType() {
        return (Integer) get(33);
    }

    /**
     * Setter for <code>public.order.logistic</code>. 物流时间
     */
    public void setLogistic(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>public.order.logistic</code>. 物流时间
     */
    public String getLogistic() {
        return (String) get(34);
    }

    /**
     * Setter for <code>public.order.area</code>.
     */
    public void setArea(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>public.order.area</code>.
     */
    public String getArea() {
        return (String) get(35);
    }

    /**
     * Setter for <code>public.order.lg_address</code>.
     */
    public void setLgAddress(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>public.order.lg_address</code>.
     */
    public String getLgAddress() {
        return (String) get(36);
    }

    /**
     * Setter for <code>public.order.lg_phone</code>.
     */
    public void setLgPhone(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>public.order.lg_phone</code>.
     */
    public String getLgPhone() {
        return (String) get(37);
    }

    /**
     * Setter for <code>public.order.lg_province</code>.
     */
    public void setLgProvince(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>public.order.lg_province</code>.
     */
    public String getLgProvince() {
        return (String) get(38);
    }

    /**
     * Setter for <code>public.order.lg_city</code>.
     */
    public void setLgCity(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>public.order.lg_city</code>.
     */
    public String getLgCity() {
        return (String) get(39);
    }

    /**
     * Setter for <code>public.order.lg_area</code>.
     */
    public void setLgArea(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>public.order.lg_area</code>.
     */
    public String getLgArea() {
        return (String) get(40);
    }

    /**
     * Setter for <code>public.order.lg_name</code>.
     */
    public void setLgName(String value) {
        set(41, value);
    }

    /**
     * Getter for <code>public.order.lg_name</code>.
     */
    public String getLgName() {
        return (String) get(41);
    }

    /**
     * Setter for <code>public.order.abandoned_reason</code>. 医生作废原因
     */
    public void setAbandonedReason(String value) {
        set(42, value);
    }

    /**
     * Getter for <code>public.order.abandoned_reason</code>. 医生作废原因
     */
    public String getAbandonedReason() {
        return (String) get(42);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderRecord
     */
    public OrderRecord() {
        super(Order.ORDER);
    }

    /**
     * Create a detached, initialised OrderRecord
     */
    public OrderRecord(Long id, String orderNo, Long createdUser, Long updatedUser, LocalDateTime createdTime, LocalDateTime updatedTime, Integer orderStatus, String ddOrderNo, Long totalPrice, Long totalPay, Long deductionAmmount, Long deliverPay, LocalDateTime payTime, LocalDateTime initTime, LocalDateTime commitTime, LocalDateTime cancelTime, LocalDateTime refundTime, Boolean prescription, Long hadPay, Long mobile, String city, Long patientId, Long leaderId, Long providerId, BigDecimal latitude, BigDecimal longitude, String address, Boolean right, String doctorName, Long rightUseId, LocalDateTime deliveredTime, Boolean rightCommit, Long rightsId, Integer shopType, String logistic, String area, String lgAddress, String lgPhone, String lgProvince, String lgCity, String lgArea, String lgName, String abandonedReason) {
        super(Order.ORDER);

        setId(id);
        setOrderNo(orderNo);
        setCreatedUser(createdUser);
        setUpdatedUser(updatedUser);
        setCreatedTime(createdTime);
        setUpdatedTime(updatedTime);
        setOrderStatus(orderStatus);
        setDdOrderNo(ddOrderNo);
        setTotalPrice(totalPrice);
        setTotalPay(totalPay);
        setDeductionAmmount(deductionAmmount);
        setDeliverPay(deliverPay);
        setPayTime(payTime);
        setInitTime(initTime);
        setCommitTime(commitTime);
        setCancelTime(cancelTime);
        setRefundTime(refundTime);
        setPrescription(prescription);
        setHadPay(hadPay);
        setMobile(mobile);
        setCity(city);
        setPatientId(patientId);
        setLeaderId(leaderId);
        setProviderId(providerId);
        setLatitude(latitude);
        setLongitude(longitude);
        setAddress(address);
        setRight(right);
        setDoctorName(doctorName);
        setRightUseId(rightUseId);
        setDeliveredTime(deliveredTime);
        setRightCommit(rightCommit);
        setRightsId(rightsId);
        setShopType(shopType);
        setLogistic(logistic);
        setArea(area);
        setLgAddress(lgAddress);
        setLgPhone(lgPhone);
        setLgProvince(lgProvince);
        setLgCity(lgCity);
        setLgArea(lgArea);
        setLgName(lgName);
        setAbandonedReason(abandonedReason);
    }

    /**
     * Create a detached, initialised OrderRecord
     */
    public OrderRecord(OrderPO value) {
        super(Order.ORDER);

        if (value != null) {
            setId(value.getId());
            setOrderNo(value.getOrderNo());
            setCreatedUser(value.getCreatedUser());
            setUpdatedUser(value.getUpdatedUser());
            setCreatedTime(value.getCreatedTime());
            setUpdatedTime(value.getUpdatedTime());
            setOrderStatus(value.getOrderStatus());
            setDdOrderNo(value.getDdOrderNo());
            setTotalPrice(value.getTotalPrice());
            setTotalPay(value.getTotalPay());
            setDeductionAmmount(value.getDeductionAmmount());
            setDeliverPay(value.getDeliverPay());
            setPayTime(value.getPayTime());
            setInitTime(value.getInitTime());
            setCommitTime(value.getCommitTime());
            setCancelTime(value.getCancelTime());
            setRefundTime(value.getRefundTime());
            setPrescription(value.getPrescription());
            setHadPay(value.getHadPay());
            setMobile(value.getMobile());
            setCity(value.getCity());
            setPatientId(value.getPatientId());
            setLeaderId(value.getLeaderId());
            setProviderId(value.getProviderId());
            setLatitude(value.getLatitude());
            setLongitude(value.getLongitude());
            setAddress(value.getAddress());
            setRight(value.getRight());
            setDoctorName(value.getDoctorName());
            setRightUseId(value.getRightUseId());
            setDeliveredTime(value.getDeliveredTime());
            setRightCommit(value.getRightCommit());
            setRightsId(value.getRightsId());
            setShopType(value.getShopType());
            setLogistic(value.getLogistic());
            setArea(value.getArea());
            setLgAddress(value.getLgAddress());
            setLgPhone(value.getLgPhone());
            setLgProvince(value.getLgProvince());
            setLgCity(value.getLgCity());
            setLgArea(value.getLgArea());
            setLgName(value.getLgName());
            setAbandonedReason(value.getAbandonedReason());
        }
    }
}
