/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.records;


import cn.yxtreme.jooq.jooq.tables.PrescriptionReview;
import cn.yxtreme.jooq.jooq.tables.pojos.PrescriptionReviewPO;

import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * 处方审核表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrescriptionReviewRecord extends TableRecordImpl<PrescriptionReviewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.prescription_review.id</code>. 自增主键

     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.prescription_review.id</code>. 自增主键

     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.prescription_review.prescription_order_id</code>.
     * 订单表id
     */
    public void setPrescriptionOrderId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.prescription_review.prescription_order_id</code>.
     * 订单表id
     */
    public Long getPrescriptionOrderId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.prescription_review.prescription_order_no</code>.
     * 订单编号
     */
    public void setPrescriptionOrderNo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.prescription_review.prescription_order_no</code>.
     * 订单编号
     */
    public String getPrescriptionOrderNo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.prescription_review.consult_order_id</code>.
     * 问诊订单id
     */
    public void setConsultOrderId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.prescription_review.consult_order_id</code>.
     * 问诊订单id
     */
    public Long getConsultOrderId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.prescription_review.apply_user_id</code>. 申请助手id
     */
    public void setApplyUserId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.prescription_review.apply_user_id</code>. 申请助手id
     */
    public Long getApplyUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.prescription_review.apply_user_name</code>.
     * 申请助手名字
     */
    public void setApplyUserName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.prescription_review.apply_user_name</code>.
     * 申请助手名字
     */
    public String getApplyUserName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.prescription_review.session_id</code>. 对应im聊天
     * 会话id
     */
    public void setSessionId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.prescription_review.session_id</code>. 对应im聊天
     * 会话id
     */
    public Long getSessionId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.prescription_review.review_user_id</code>. 审核人id
     */
    public void setReviewUserId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.prescription_review.review_user_id</code>. 审核人id
     */
    public Long getReviewUserId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.prescription_review.review_user_name</code>.
     * 审核人姓名
     */
    public void setReviewUserName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.prescription_review.review_user_name</code>.
     * 审核人姓名
     */
    public String getReviewUserName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.prescription_review.status</code>. 审核状态
     * 0:待审核
     * 1:审核通过
     * 2:驳回
     * 3:流转
     * 4:流转失败 等待再次流转
     */
    public void setStatus(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.prescription_review.status</code>. 审核状态
     * 0:待审核
     * 1:审核通过
     * 2:驳回
     * 3:流转
     * 4:流转失败 等待再次流转
     */
    public Integer getStatus() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.prescription_review.created_at</code>. 创建时间
     */
    public void setCreatedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.prescription_review.created_at</code>. 创建时间
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>public.prescription_review.updated_at</code>. 更新时间
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.prescription_review.updated_at</code>. 更新时间
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.prescription_review.handler_user_id</code>.
     * 工作站指定的处理人id
     */
    public void setHandlerUserId(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.prescription_review.handler_user_id</code>.
     * 工作站指定的处理人id
     */
    public Long getHandlerUserId() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.prescription_review.handler_user_name</code>.
     * 工作站指定的处理人name
     */
    public void setHandlerUserName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.prescription_review.handler_user_name</code>.
     * 工作站指定的处理人name
     */
    public String getHandlerUserName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.prescription_review.reject_content</code>. 驳回原因
     */
    public void setRejectContent(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.prescription_review.reject_content</code>. 驳回原因
     */
    public String getRejectContent() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.prescription_review.arrangement_id</code>. 药单id
     */
    public void setArrangementId(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.prescription_review.arrangement_id</code>. 药单id
     */
    public Long getArrangementId() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>public.prescription_review.department_name</code>. 科室名
     */
    public void setDepartmentName(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.prescription_review.department_name</code>. 科室名
     */
    public String getDepartmentName() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.prescription_review.router_time</code>. 流转时间
     */
    public void setRouterTime(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.prescription_review.router_time</code>. 流转时间
     */
    public LocalDateTime getRouterTime() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>public.prescription_review.router_user_id</code>. 流转用户
     */
    public void setRouterUserId(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.prescription_review.router_user_id</code>. 流转用户
     */
    public Long getRouterUserId() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>public.prescription_review.router_user_name</code>.
     * 流转用户名
     */
    public void setRouterUserName(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.prescription_review.router_user_name</code>.
     * 流转用户名
     */
    public String getRouterUserName() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.prescription_review.review_time</code>. 审核时间
     */
    public void setReviewTime(LocalDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.prescription_review.review_time</code>. 审核时间
     */
    public LocalDateTime getReviewTime() {
        return (LocalDateTime) get(20);
    }

    /**
     * Setter for <code>public.prescription_review.provider_name</code>.
     */
    public void setProviderName(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.prescription_review.provider_name</code>.
     */
    public String getProviderName() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.prescription_review.provider_id</code>.
     */
    public void setProviderId(Long value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.prescription_review.provider_id</code>.
     */
    public Long getProviderId() {
        return (Long) get(22);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PrescriptionReviewRecord
     */
    public PrescriptionReviewRecord() {
        super(PrescriptionReview.PRESCRIPTION_REVIEW);
    }

    /**
     * Create a detached, initialised PrescriptionReviewRecord
     */
    public PrescriptionReviewRecord(Long id, Long prescriptionOrderId, String prescriptionOrderNo, Long consultOrderId, Long applyUserId, String applyUserName, Long sessionId, Long reviewUserId, String reviewUserName, Integer status, LocalDateTime createdAt, LocalDateTime updatedAt, Long handlerUserId, String handlerUserName, String rejectContent, Long arrangementId, String departmentName, LocalDateTime routerTime, Long routerUserId, String routerUserName, LocalDateTime reviewTime, String providerName, Long providerId) {
        super(PrescriptionReview.PRESCRIPTION_REVIEW);

        setId(id);
        setPrescriptionOrderId(prescriptionOrderId);
        setPrescriptionOrderNo(prescriptionOrderNo);
        setConsultOrderId(consultOrderId);
        setApplyUserId(applyUserId);
        setApplyUserName(applyUserName);
        setSessionId(sessionId);
        setReviewUserId(reviewUserId);
        setReviewUserName(reviewUserName);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setHandlerUserId(handlerUserId);
        setHandlerUserName(handlerUserName);
        setRejectContent(rejectContent);
        setArrangementId(arrangementId);
        setDepartmentName(departmentName);
        setRouterTime(routerTime);
        setRouterUserId(routerUserId);
        setRouterUserName(routerUserName);
        setReviewTime(reviewTime);
        setProviderName(providerName);
        setProviderId(providerId);
    }

    /**
     * Create a detached, initialised PrescriptionReviewRecord
     */
    public PrescriptionReviewRecord(PrescriptionReviewPO value) {
        super(PrescriptionReview.PRESCRIPTION_REVIEW);

        if (value != null) {
            setId(value.getId());
            setPrescriptionOrderId(value.getPrescriptionOrderId());
            setPrescriptionOrderNo(value.getPrescriptionOrderNo());
            setConsultOrderId(value.getConsultOrderId());
            setApplyUserId(value.getApplyUserId());
            setApplyUserName(value.getApplyUserName());
            setSessionId(value.getSessionId());
            setReviewUserId(value.getReviewUserId());
            setReviewUserName(value.getReviewUserName());
            setStatus(value.getStatus());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            setHandlerUserId(value.getHandlerUserId());
            setHandlerUserName(value.getHandlerUserName());
            setRejectContent(value.getRejectContent());
            setArrangementId(value.getArrangementId());
            setDepartmentName(value.getDepartmentName());
            setRouterTime(value.getRouterTime());
            setRouterUserId(value.getRouterUserId());
            setRouterUserName(value.getRouterUserName());
            setReviewTime(value.getReviewTime());
            setProviderName(value.getProviderName());
            setProviderId(value.getProviderId());
        }
    }
}
