/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.records;


import cn.yxtreme.jooq.jooq.tables.RegularUsage;
import cn.yxtreme.jooq.jooq.tables.pojos.RegularUsagePO;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RegularUsageRecord extends UpdatableRecordImpl<RegularUsageRecord> implements Record15<Long, String, String, String, String, String, String, String, String, String, String, Boolean, LocalDateTime, LocalDateTime, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.regular_usage.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.regular_usage.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.regular_usage.usage</code>. 用法
     */
    public void setUsage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.regular_usage.usage</code>. 用法
     */
    public String getUsage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.regular_usage.dosage</code>. 用量
     */
    public void setDosage(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.regular_usage.dosage</code>. 用量
     */
    public String getDosage() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.regular_usage.sku</code>. sku
     */
    public void setSku(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.regular_usage.sku</code>. sku
     */
    public String getSku() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.regular_usage.usage_unit</code>. 用法单位
     */
    public void setUsageUnit(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.regular_usage.usage_unit</code>. 用法单位
     */
    public String getUsageUnit() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.regular_usage.use_time</code>. 用频
     */
    public void setUseTime(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.regular_usage.use_time</code>. 用频
     */
    public String getUseTime() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.regular_usage.use_time_unit</code>. 用频单位
     */
    public void setUseTimeUnit(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.regular_usage.use_time_unit</code>. 用频单位
     */
    public String getUseTimeUnit() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.regular_usage.adverse_reactions</code>. 不良反应
     */
    public void setAdverseReactions(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.regular_usage.adverse_reactions</code>. 不良反应
     */
    public String getAdverseReactions() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.regular_usage.forbiddance</code>. 禁忌
     */
    public void setForbiddance(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.regular_usage.forbiddance</code>. 禁忌
     */
    public String getForbiddance() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.regular_usage.attention</code>. 注意事项
     */
    public void setAttention(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.regular_usage.attention</code>. 注意事项
     */
    public String getAttention() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.regular_usage.interaction</code>. 相互作用
     */
    public void setInteraction(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.regular_usage.interaction</code>. 相互作用
     */
    public String getInteraction() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.regular_usage.deleted</code>.
     */
    public void setDeleted(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.regular_usage.deleted</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>public.regular_usage.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.regular_usage.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>public.regular_usage.updated</code>.
     */
    public void setUpdated(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.regular_usage.updated</code>.
     */
    public LocalDateTime getUpdated() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>public.regular_usage.version</code>.
     */
    public void setVersion(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.regular_usage.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<Long, String, String, String, String, String, String, String, String, String, String, Boolean, LocalDateTime, LocalDateTime, Integer> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Long, String, String, String, String, String, String, String, String, String, String, Boolean, LocalDateTime, LocalDateTime, Integer> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return RegularUsage.REGULAR_USAGE.ID;
    }

    @Override
    public Field<String> field2() {
        return RegularUsage.REGULAR_USAGE.USAGE;
    }

    @Override
    public Field<String> field3() {
        return RegularUsage.REGULAR_USAGE.DOSAGE;
    }

    @Override
    public Field<String> field4() {
        return RegularUsage.REGULAR_USAGE.SKU;
    }

    @Override
    public Field<String> field5() {
        return RegularUsage.REGULAR_USAGE.USAGE_UNIT;
    }

    @Override
    public Field<String> field6() {
        return RegularUsage.REGULAR_USAGE.USE_TIME;
    }

    @Override
    public Field<String> field7() {
        return RegularUsage.REGULAR_USAGE.USE_TIME_UNIT;
    }

    @Override
    public Field<String> field8() {
        return RegularUsage.REGULAR_USAGE.ADVERSE_REACTIONS;
    }

    @Override
    public Field<String> field9() {
        return RegularUsage.REGULAR_USAGE.FORBIDDANCE;
    }

    @Override
    public Field<String> field10() {
        return RegularUsage.REGULAR_USAGE.ATTENTION;
    }

    @Override
    public Field<String> field11() {
        return RegularUsage.REGULAR_USAGE.INTERACTION;
    }

    @Override
    public Field<Boolean> field12() {
        return RegularUsage.REGULAR_USAGE.DELETED;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return RegularUsage.REGULAR_USAGE.CREATED;
    }

    @Override
    public Field<LocalDateTime> field14() {
        return RegularUsage.REGULAR_USAGE.UPDATED;
    }

    @Override
    public Field<Integer> field15() {
        return RegularUsage.REGULAR_USAGE.VERSION;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUsage();
    }

    @Override
    public String component3() {
        return getDosage();
    }

    @Override
    public String component4() {
        return getSku();
    }

    @Override
    public String component5() {
        return getUsageUnit();
    }

    @Override
    public String component6() {
        return getUseTime();
    }

    @Override
    public String component7() {
        return getUseTimeUnit();
    }

    @Override
    public String component8() {
        return getAdverseReactions();
    }

    @Override
    public String component9() {
        return getForbiddance();
    }

    @Override
    public String component10() {
        return getAttention();
    }

    @Override
    public String component11() {
        return getInteraction();
    }

    @Override
    public Boolean component12() {
        return getDeleted();
    }

    @Override
    public LocalDateTime component13() {
        return getCreated();
    }

    @Override
    public LocalDateTime component14() {
        return getUpdated();
    }

    @Override
    public Integer component15() {
        return getVersion();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUsage();
    }

    @Override
    public String value3() {
        return getDosage();
    }

    @Override
    public String value4() {
        return getSku();
    }

    @Override
    public String value5() {
        return getUsageUnit();
    }

    @Override
    public String value6() {
        return getUseTime();
    }

    @Override
    public String value7() {
        return getUseTimeUnit();
    }

    @Override
    public String value8() {
        return getAdverseReactions();
    }

    @Override
    public String value9() {
        return getForbiddance();
    }

    @Override
    public String value10() {
        return getAttention();
    }

    @Override
    public String value11() {
        return getInteraction();
    }

    @Override
    public Boolean value12() {
        return getDeleted();
    }

    @Override
    public LocalDateTime value13() {
        return getCreated();
    }

    @Override
    public LocalDateTime value14() {
        return getUpdated();
    }

    @Override
    public Integer value15() {
        return getVersion();
    }

    @Override
    public RegularUsageRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public RegularUsageRecord value2(String value) {
        setUsage(value);
        return this;
    }

    @Override
    public RegularUsageRecord value3(String value) {
        setDosage(value);
        return this;
    }

    @Override
    public RegularUsageRecord value4(String value) {
        setSku(value);
        return this;
    }

    @Override
    public RegularUsageRecord value5(String value) {
        setUsageUnit(value);
        return this;
    }

    @Override
    public RegularUsageRecord value6(String value) {
        setUseTime(value);
        return this;
    }

    @Override
    public RegularUsageRecord value7(String value) {
        setUseTimeUnit(value);
        return this;
    }

    @Override
    public RegularUsageRecord value8(String value) {
        setAdverseReactions(value);
        return this;
    }

    @Override
    public RegularUsageRecord value9(String value) {
        setForbiddance(value);
        return this;
    }

    @Override
    public RegularUsageRecord value10(String value) {
        setAttention(value);
        return this;
    }

    @Override
    public RegularUsageRecord value11(String value) {
        setInteraction(value);
        return this;
    }

    @Override
    public RegularUsageRecord value12(Boolean value) {
        setDeleted(value);
        return this;
    }

    @Override
    public RegularUsageRecord value13(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public RegularUsageRecord value14(LocalDateTime value) {
        setUpdated(value);
        return this;
    }

    @Override
    public RegularUsageRecord value15(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public RegularUsageRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, Boolean value12, LocalDateTime value13, LocalDateTime value14, Integer value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RegularUsageRecord
     */
    public RegularUsageRecord() {
        super(RegularUsage.REGULAR_USAGE);
    }

    /**
     * Create a detached, initialised RegularUsageRecord
     */
    public RegularUsageRecord(Long id, String usage, String dosage, String sku, String usageUnit, String useTime, String useTimeUnit, String adverseReactions, String forbiddance, String attention, String interaction, Boolean deleted, LocalDateTime created, LocalDateTime updated, Integer version) {
        super(RegularUsage.REGULAR_USAGE);

        setId(id);
        setUsage(usage);
        setDosage(dosage);
        setSku(sku);
        setUsageUnit(usageUnit);
        setUseTime(useTime);
        setUseTimeUnit(useTimeUnit);
        setAdverseReactions(adverseReactions);
        setForbiddance(forbiddance);
        setAttention(attention);
        setInteraction(interaction);
        setDeleted(deleted);
        setCreated(created);
        setUpdated(updated);
        setVersion(version);
    }

    /**
     * Create a detached, initialised RegularUsageRecord
     */
    public RegularUsageRecord(RegularUsagePO value) {
        super(RegularUsage.REGULAR_USAGE);

        if (value != null) {
            setId(value.getId());
            setUsage(value.getUsage());
            setDosage(value.getDosage());
            setSku(value.getSku());
            setUsageUnit(value.getUsageUnit());
            setUseTime(value.getUseTime());
            setUseTimeUnit(value.getUseTimeUnit());
            setAdverseReactions(value.getAdverseReactions());
            setForbiddance(value.getForbiddance());
            setAttention(value.getAttention());
            setInteraction(value.getInteraction());
            setDeleted(value.getDeleted());
            setCreated(value.getCreated());
            setUpdated(value.getUpdated());
            setVersion(value.getVersion());
        }
    }
}
