/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.records;


import cn.yxtreme.jooq.jooq.tables.Shop;
import cn.yxtreme.jooq.jooq.tables.pojos.ShopPO;

import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopRecord extends TableRecordImpl<ShopRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.shop.id</code>. 主键id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.shop.id</code>. 主键id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.shop.order_id</code>. 订单id
     */
    public void setOrderId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.shop.order_id</code>. 订单id
     */
    public Long getOrderId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.shop.total_dosage</code>. 数量
     */
    public void setTotalDosage(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.shop.total_dosage</code>. 数量
     */
    public Long getTotalDosage() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.shop.dosage</code>. 单次用药剂量
     */
    public void setDosage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.shop.dosage</code>. 单次用药剂量
     */
    public String getDosage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.shop.dosage_unit</code>. 单次用药剂量单位
     */
    public void setDosageUnit(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.shop.dosage_unit</code>. 单次用药剂量单位
     */
    public String getDosageUnit() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.shop.medicine_freq</code>. 用药评率
     */
    public void setMedicineFreq(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.shop.medicine_freq</code>. 用药评率
     */
    public String getMedicineFreq() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.shop.comments</code>. 嘱托
     */
    public void setComments(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.shop.comments</code>. 嘱托
     */
    public String getComments() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.shop.total_charge</code>. 服药天数
     */
    public void setTotalCharge(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.shop.total_charge</code>. 服药天数
     */
    public Long getTotalCharge() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.shop.prescription</code>. 是否处方药
     */
    public void setPrescription(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.shop.prescription</code>. 是否处方药
     */
    public Boolean getPrescription() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.shop.name</code>. 商品名
     */
    public void setName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.shop.name</code>. 商品名
     */
    public String getName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.shop.spec</code>. 规格
     */
    public void setSpec(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.shop.spec</code>. 规格
     */
    public String getSpec() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.shop.brand_name</code>. 品牌
     */
    public void setBrandName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.shop.brand_name</code>. 品牌
     */
    public String getBrandName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.shop.usage</code>. 用法
     */
    public void setUsage(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.shop.usage</code>. 用法
     */
    public String getUsage() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.shop.price</code>. 价格 单位分
     */
    public void setPrice(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.shop.price</code>. 价格 单位分
     */
    public Long getPrice() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>public.shop.created_time</code>.
     */
    public void setCreatedTime(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.shop.created_time</code>.
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>public.shop.updated_time</code>. current_timestamp
     */
    public void setUpdatedTime(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.shop.updated_time</code>. current_timestamp
     */
    public LocalDateTime getUpdatedTime() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>public.shop.arrangement_id</code>. 药单表id
     */
    public void setArrangementId(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.shop.arrangement_id</code>. 药单表id
     */
    public Long getArrangementId() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>public.shop.sku_id</code>. 叮当skuId
     */
    public void setSkuId(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.shop.sku_id</code>. 叮当skuId
     */
    public Long getSkuId() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>public.shop.big_img_url</code>. 大图地址url多个 以｜分割
     */
    public void setBigImgUrl(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.shop.big_img_url</code>. 大图地址url多个 以｜分割
     */
    public String getBigImgUrl() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.shop.small_img_url</code>. 小图地址url
     */
    public void setSmallImgUrl(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.shop.small_img_url</code>. 小图地址url
     */
    public String getSmallImgUrl() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.shop.mid_img_url</code>. 中图 图片url地址
     */
    public void setMidImgUrl(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.shop.mid_img_url</code>. 中图 图片url地址
     */
    public String getMidImgUrl() {
        return (String) get(20);
    }

    /**
     * Setter for <code>public.shop.total_dosage_unit</code>.
     */
    public void setTotalDosageUnit(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.shop.total_dosage_unit</code>.
     */
    public String getTotalDosageUnit() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.shop.original_price</code>. 原价
     */
    public void setOriginalPrice(Long value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.shop.original_price</code>. 原价
     */
    public Long getOriginalPrice() {
        return (Long) get(22);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShopRecord
     */
    public ShopRecord() {
        super(Shop.SHOP);
    }

    /**
     * Create a detached, initialised ShopRecord
     */
    public ShopRecord(Long id, Long orderId, Long totalDosage, String dosage, String dosageUnit, String medicineFreq, String comments, Long totalCharge, Boolean prescription, String name, String spec, String brandName, String usage, Long price, LocalDateTime createdTime, LocalDateTime updatedTime, Long arrangementId, Long skuId, String bigImgUrl, String smallImgUrl, String midImgUrl, String totalDosageUnit, Long originalPrice) {
        super(Shop.SHOP);

        setId(id);
        setOrderId(orderId);
        setTotalDosage(totalDosage);
        setDosage(dosage);
        setDosageUnit(dosageUnit);
        setMedicineFreq(medicineFreq);
        setComments(comments);
        setTotalCharge(totalCharge);
        setPrescription(prescription);
        setName(name);
        setSpec(spec);
        setBrandName(brandName);
        setUsage(usage);
        setPrice(price);
        setCreatedTime(createdTime);
        setUpdatedTime(updatedTime);
        setArrangementId(arrangementId);
        setSkuId(skuId);
        setBigImgUrl(bigImgUrl);
        setSmallImgUrl(smallImgUrl);
        setMidImgUrl(midImgUrl);
        setTotalDosageUnit(totalDosageUnit);
        setOriginalPrice(originalPrice);
    }

    /**
     * Create a detached, initialised ShopRecord
     */
    public ShopRecord(ShopPO value) {
        super(Shop.SHOP);

        if (value != null) {
            setId(value.getId());
            setOrderId(value.getOrderId());
            setTotalDosage(value.getTotalDosage());
            setDosage(value.getDosage());
            setDosageUnit(value.getDosageUnit());
            setMedicineFreq(value.getMedicineFreq());
            setComments(value.getComments());
            setTotalCharge(value.getTotalCharge());
            setPrescription(value.getPrescription());
            setName(value.getName());
            setSpec(value.getSpec());
            setBrandName(value.getBrandName());
            setUsage(value.getUsage());
            setPrice(value.getPrice());
            setCreatedTime(value.getCreatedTime());
            setUpdatedTime(value.getUpdatedTime());
            setArrangementId(value.getArrangementId());
            setSkuId(value.getSkuId());
            setBigImgUrl(value.getBigImgUrl());
            setSmallImgUrl(value.getSmallImgUrl());
            setMidImgUrl(value.getMidImgUrl());
            setTotalDosageUnit(value.getTotalDosageUnit());
            setOriginalPrice(value.getOriginalPrice());
        }
    }
}
