/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq;


import cn.yxtreme.jooq.jooq.tables.Arrangement;
import cn.yxtreme.jooq.jooq.tables.Fence;
import cn.yxtreme.jooq.jooq.tables.MedicineV2;
import cn.yxtreme.jooq.jooq.tables.PrescriptionReview;
import cn.yxtreme.jooq.jooq.tables.RegularUsage;
import cn.yxtreme.jooq.jooq.tables.RegularUsageCount;
import cn.yxtreme.jooq.jooq.tables.UsageDictionary;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FENCE_PROVINCE_CODE_UINDEX = Internal.createIndex(DSL.name("fence_province_code_uindex"), Fence.FENCE, new OrderField[] { Fence.FENCE.PROVINCE_CODE }, true);
    public static final Index IDX_ORDER_ID = Internal.createIndex(DSL.name("idx_order_id"), Arrangement.ARRANGEMENT, new OrderField[] { Arrangement.ARRANGEMENT.ORDER_ID }, false);
    public static final Index IDX_ORDER_V2_ID = Internal.createIndex(DSL.name("idx_order_v2_id"), MedicineV2.MEDICINE_V2, new OrderField[] { MedicineV2.MEDICINE_V2.CONSULT_ORDER_ID }, false);
    public static final Index PRESCRIPTION_REVIEW__ARRID = Internal.createIndex(DSL.name("prescription_review__arrid"), PrescriptionReview.PRESCRIPTION_REVIEW, new OrderField[] { PrescriptionReview.PRESCRIPTION_REVIEW.ARRANGEMENT_ID }, false);
    public static final Index PRESCRIPTION_REVIEW_STATUS_IDX = Internal.createIndex(DSL.name("prescription_review_status_idx"), PrescriptionReview.PRESCRIPTION_REVIEW, new OrderField[] { PrescriptionReview.PRESCRIPTION_REVIEW.STATUS }, false);
    public static final Index REGULAR_USAGE_COUNT_SKU_CREATED_IDX = Internal.createIndex(DSL.name("regular_usage_count_sku_created_idx"), RegularUsageCount.REGULAR_USAGE_COUNT, new OrderField[] { RegularUsageCount.REGULAR_USAGE_COUNT.SKU, RegularUsageCount.REGULAR_USAGE_COUNT.CREATED }, false);
    public static final Index REGULAR_USAGE_SKU_IDX_COPY1 = Internal.createIndex(DSL.name("regular_usage_sku_idx_copy1"), RegularUsage.REGULAR_USAGE, new OrderField[] { RegularUsage.REGULAR_USAGE.SKU }, true);
    public static final Index USAGE_DICTIONARY_CONCEPT_KEY_IDX = Internal.createIndex(DSL.name("usage_dictionary_concept_key_idx"), UsageDictionary.USAGE_DICTIONARY, new OrderField[] { UsageDictionary.USAGE_DICTIONARY.CONCEPT, UsageDictionary.USAGE_DICTIONARY.KEY }, true);
}
