/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq;


import cn.yxtreme.jooq.jooq.tables.Arrangement;
import cn.yxtreme.jooq.jooq.tables.ChineseMedicine;
import cn.yxtreme.jooq.jooq.tables.ExpressDelivery;
import cn.yxtreme.jooq.jooq.tables.Fence;
import cn.yxtreme.jooq.jooq.tables.InterfaceRecord;
import cn.yxtreme.jooq.jooq.tables.MedicineOrder;
import cn.yxtreme.jooq.jooq.tables.MedicineOrderFlow;
import cn.yxtreme.jooq.jooq.tables.MedicineOrderReceive;
import cn.yxtreme.jooq.jooq.tables.MedicineV2;
import cn.yxtreme.jooq.jooq.tables.NormalMedication;
import cn.yxtreme.jooq.jooq.tables.NormalMedicationPart;
import cn.yxtreme.jooq.jooq.tables.Order;
import cn.yxtreme.jooq.jooq.tables.OrderV2;
import cn.yxtreme.jooq.jooq.tables.PrescriptionReview;
import cn.yxtreme.jooq.jooq.tables.RegularUsage;
import cn.yxtreme.jooq.jooq.tables.RegularUsageCount;
import cn.yxtreme.jooq.jooq.tables.Shop;
import cn.yxtreme.jooq.jooq.tables.UsageDictionary;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * 开药表
     */
    public final Arrangement ARRANGEMENT = Arrangement.ARRANGEMENT;

    /**
     * 中药表
     */
    public final ChineseMedicine CHINESE_MEDICINE = ChineseMedicine.CHINESE_MEDICINE;

    /**
     * The table <code>public.express_delivery</code>.
     */
    public final ExpressDelivery EXPRESS_DELIVERY = ExpressDelivery.EXPRESS_DELIVERY;

    /**
     * 地理围栏
     */
    public final Fence FENCE = Fence.FENCE;

    /**
     * 接口调用记录表
     */
    public final InterfaceRecord INTERFACE_RECORD = InterfaceRecord.INTERFACE_RECORD;

    /**
     * 订单表
     */
    public final MedicineOrder MEDICINE_ORDER = MedicineOrder.MEDICINE_ORDER;

    /**
     * The table <code>public.medicine_order_flow</code>.
     */
    public final MedicineOrderFlow MEDICINE_ORDER_FLOW = MedicineOrderFlow.MEDICINE_ORDER_FLOW;

    /**
     * 订单表
     */
    public final MedicineOrderReceive MEDICINE_ORDER_RECEIVE = MedicineOrderReceive.MEDICINE_ORDER_RECEIVE;

    /**
     * 开药表
     */
    public final MedicineV2 MEDICINE_V2 = MedicineV2.MEDICINE_V2;

    /**
     * 标准方
     */
    public final NormalMedication NORMAL_MEDICATION = NormalMedication.NORMAL_MEDICATION;

    /**
     * 标准方组成表
     */
    public final NormalMedicationPart NORMAL_MEDICATION_PART = NormalMedicationPart.NORMAL_MEDICATION_PART;

    /**
     * 订单表
     */
    public final Order ORDER = Order.ORDER;

    /**
     * 订单表
     */
    public final OrderV2 ORDER_V2 = OrderV2.ORDER_V2;

    /**
     * 处方审核表
     */
    public final PrescriptionReview PRESCRIPTION_REVIEW = PrescriptionReview.PRESCRIPTION_REVIEW;

    /**
     * The table <code>public.regular_usage</code>.
     */
    public final RegularUsage REGULAR_USAGE = RegularUsage.REGULAR_USAGE;

    /**
     * The table <code>public.regular_usage_count</code>.
     */
    public final RegularUsageCount REGULAR_USAGE_COUNT = RegularUsageCount.REGULAR_USAGE_COUNT;

    /**
     * The table <code>public.shop</code>.
     */
    public final Shop SHOP = Shop.SHOP;

    /**
     * The table <code>public.usage_dictionary</code>.
     */
    public final UsageDictionary USAGE_DICTIONARY = UsageDictionary.USAGE_DICTIONARY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.ARRANGEMENT_V2_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Arrangement.ARRANGEMENT,
            ChineseMedicine.CHINESE_MEDICINE,
            ExpressDelivery.EXPRESS_DELIVERY,
            Fence.FENCE,
            InterfaceRecord.INTERFACE_RECORD,
            MedicineOrder.MEDICINE_ORDER,
            MedicineOrderFlow.MEDICINE_ORDER_FLOW,
            MedicineOrderReceive.MEDICINE_ORDER_RECEIVE,
            MedicineV2.MEDICINE_V2,
            NormalMedication.NORMAL_MEDICATION,
            NormalMedicationPart.NORMAL_MEDICATION_PART,
            Order.ORDER,
            OrderV2.ORDER_V2,
            PrescriptionReview.PRESCRIPTION_REVIEW,
            RegularUsage.REGULAR_USAGE,
            RegularUsageCount.REGULAR_USAGE_COUNT,
            Shop.SHOP,
            UsageDictionary.USAGE_DICTIONARY
        );
    }
}
