/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.arrangement_v2_id_seq</code>
     */
    public static final Sequence<Long> ARRANGEMENT_V2_ID_SEQ = Internal.createSequence("arrangement_v2_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
