/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.daos;


import cn.yxtreme.jooq.jooq.tables.ChineseMedicine;
import cn.yxtreme.jooq.jooq.tables.pojos.ChineseMedicinePO;
import cn.yxtreme.jooq.jooq.tables.records.ChineseMedicineRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 中药表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChineseMedicineDao extends DAOImpl<ChineseMedicineRecord, ChineseMedicinePO, Long> {

    /**
     * Create a new ChineseMedicineDao without any configuration
     */
    public ChineseMedicineDao() {
        super(ChineseMedicine.CHINESE_MEDICINE, ChineseMedicinePO.class);
    }

    /**
     * Create a new ChineseMedicineDao with an attached configuration
     */
    public ChineseMedicineDao(Configuration configuration) {
        super(ChineseMedicine.CHINESE_MEDICINE, ChineseMedicinePO.class, configuration);
    }

    @Override
    public Long getId(ChineseMedicinePO object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ChineseMedicinePO> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ChineseMedicine.CHINESE_MEDICINE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ChineseMedicinePO> fetchById(Long... values) {
        return fetch(ChineseMedicine.CHINESE_MEDICINE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ChineseMedicinePO fetchOneById(Long value) {
        return fetchOne(ChineseMedicine.CHINESE_MEDICINE.ID, value);
    }

    /**
     * Fetch records that have <code>herb_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ChineseMedicinePO> fetchRangeOfHerbName(String lowerInclusive, String upperInclusive) {
        return fetchRange(ChineseMedicine.CHINESE_MEDICINE.HERB_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>herb_name IN (values)</code>
     */
    public List<ChineseMedicinePO> fetchByHerbName(String... values) {
        return fetch(ChineseMedicine.CHINESE_MEDICINE.HERB_NAME, values);
    }

    /**
     * Fetch records that have <code>sku_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ChineseMedicinePO> fetchRangeOfSkuId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ChineseMedicine.CHINESE_MEDICINE.SKU_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sku_id IN (values)</code>
     */
    public List<ChineseMedicinePO> fetchBySkuId(Long... values) {
        return fetch(ChineseMedicine.CHINESE_MEDICINE.SKU_ID, values);
    }

    /**
     * Fetch records that have <code>settlement_price BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ChineseMedicinePO> fetchRangeOfSettlementPrice(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ChineseMedicine.CHINESE_MEDICINE.SETTLEMENT_PRICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>settlement_price IN (values)</code>
     */
    public List<ChineseMedicinePO> fetchBySettlementPrice(BigDecimal... values) {
        return fetch(ChineseMedicine.CHINESE_MEDICINE.SETTLEMENT_PRICE, values);
    }

    /**
     * Fetch records that have <code>created_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ChineseMedicinePO> fetchRangeOfCreatedTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ChineseMedicine.CHINESE_MEDICINE.CREATED_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_time IN (values)</code>
     */
    public List<ChineseMedicinePO> fetchByCreatedTime(LocalDateTime... values) {
        return fetch(ChineseMedicine.CHINESE_MEDICINE.CREATED_TIME, values);
    }

    /**
     * Fetch records that have <code>updated_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ChineseMedicinePO> fetchRangeOfUpdatedTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ChineseMedicine.CHINESE_MEDICINE.UPDATED_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_time IN (values)</code>
     */
    public List<ChineseMedicinePO> fetchByUpdatedTime(LocalDateTime... values) {
        return fetch(ChineseMedicine.CHINESE_MEDICINE.UPDATED_TIME, values);
    }

    /**
     * Fetch records that have <code>deleted BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ChineseMedicinePO> fetchRangeOfDeleted(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(ChineseMedicine.CHINESE_MEDICINE.DELETED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>deleted IN (values)</code>
     */
    public List<ChineseMedicinePO> fetchByDeleted(Boolean... values) {
        return fetch(ChineseMedicine.CHINESE_MEDICINE.DELETED, values);
    }

    /**
     * Fetch records that have <code>sell_price BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ChineseMedicinePO> fetchRangeOfSellPrice(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ChineseMedicine.CHINESE_MEDICINE.SELL_PRICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sell_price IN (values)</code>
     */
    public List<ChineseMedicinePO> fetchBySellPrice(BigDecimal... values) {
        return fetch(ChineseMedicine.CHINESE_MEDICINE.SELL_PRICE, values);
    }

    /**
     * Fetch records that have <code>reference_price BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ChineseMedicinePO> fetchRangeOfReferencePrice(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ChineseMedicine.CHINESE_MEDICINE.REFERENCE_PRICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>reference_price IN (values)</code>
     */
    public List<ChineseMedicinePO> fetchByReferencePrice(BigDecimal... values) {
        return fetch(ChineseMedicine.CHINESE_MEDICINE.REFERENCE_PRICE, values);
    }
        public List<ChineseMedicinePO> fetchById(Collection<Long> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.ChineseMedicine.CHINESE_MEDICINE.ID, value.toArray(new Long[value.size()]));
        }
        public List<ChineseMedicinePO> fetchByHerbName(Collection<String> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.ChineseMedicine.CHINESE_MEDICINE.HERB_NAME, value.toArray(new String[value.size()]));
        }
        public List<ChineseMedicinePO> fetchBySkuId(Collection<Long> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.ChineseMedicine.CHINESE_MEDICINE.SKU_ID, value.toArray(new Long[value.size()]));
        }
        public List<ChineseMedicinePO> fetchBySettlementPrice(Collection<BigDecimal> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.ChineseMedicine.CHINESE_MEDICINE.SETTLEMENT_PRICE, value.toArray(new BigDecimal[value.size()]));
        }
        public List<ChineseMedicinePO> fetchByCreatedTime(Collection<LocalDateTime> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.ChineseMedicine.CHINESE_MEDICINE.CREATED_TIME, value.toArray(new LocalDateTime[value.size()]));
        }
        public List<ChineseMedicinePO> fetchByUpdatedTime(Collection<LocalDateTime> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.ChineseMedicine.CHINESE_MEDICINE.UPDATED_TIME, value.toArray(new LocalDateTime[value.size()]));
        }
        public List<ChineseMedicinePO> fetchByDeleted(Collection<Boolean> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.ChineseMedicine.CHINESE_MEDICINE.DELETED, value.toArray(new Boolean[value.size()]));
        }
        public List<ChineseMedicinePO> fetchBySellPrice(Collection<BigDecimal> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.ChineseMedicine.CHINESE_MEDICINE.SELL_PRICE, value.toArray(new BigDecimal[value.size()]));
        }
        public List<ChineseMedicinePO> fetchByReferencePrice(Collection<BigDecimal> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.ChineseMedicine.CHINESE_MEDICINE.REFERENCE_PRICE, value.toArray(new BigDecimal[value.size()]));
        }
}
