/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.daos;


import cn.yxtreme.jooq.jooq.tables.MedicineOrderReceive;
import cn.yxtreme.jooq.jooq.tables.pojos.MedicineOrderReceivePO;
import cn.yxtreme.jooq.jooq.tables.records.MedicineOrderReceiveRecord;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 订单表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedicineOrderReceiveDao extends DAOImpl<MedicineOrderReceiveRecord, MedicineOrderReceivePO, Long> {

    /**
     * Create a new MedicineOrderReceiveDao without any configuration
     */
    public MedicineOrderReceiveDao() {
        super(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE, MedicineOrderReceivePO.class);
    }

    /**
     * Create a new MedicineOrderReceiveDao with an attached configuration
     */
    public MedicineOrderReceiveDao(Configuration configuration) {
        super(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE, MedicineOrderReceivePO.class, configuration);
    }

    @Override
    public Long getId(MedicineOrderReceivePO object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<MedicineOrderReceivePO> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<MedicineOrderReceivePO> fetchById(Long... values) {
        return fetch(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public MedicineOrderReceivePO fetchOneById(Long value) {
        return fetchOne(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.ID, value);
    }

    /**
     * Fetch records that have <code>created_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<MedicineOrderReceivePO> fetchRangeOfCreatedTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.CREATED_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_time IN (values)</code>
     */
    public List<MedicineOrderReceivePO> fetchByCreatedTime(LocalDateTime... values) {
        return fetch(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.CREATED_TIME, values);
    }

    /**
     * Fetch records that have <code>medicine_order_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<MedicineOrderReceivePO> fetchRangeOfMedicineOrderId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.MEDICINE_ORDER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>medicine_order_id IN (values)</code>
     */
    public List<MedicineOrderReceivePO> fetchByMedicineOrderId(Long... values) {
        return fetch(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.MEDICINE_ORDER_ID, values);
    }

    /**
     * Fetch records that have <code>lg_province BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<MedicineOrderReceivePO> fetchRangeOfLgProvince(String lowerInclusive, String upperInclusive) {
        return fetchRange(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_PROVINCE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lg_province IN (values)</code>
     */
    public List<MedicineOrderReceivePO> fetchByLgProvince(String... values) {
        return fetch(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_PROVINCE, values);
    }

    /**
     * Fetch records that have <code>lg_province_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<MedicineOrderReceivePO> fetchRangeOfLgProvinceCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_PROVINCE_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lg_province_code IN (values)</code>
     */
    public List<MedicineOrderReceivePO> fetchByLgProvinceCode(String... values) {
        return fetch(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_PROVINCE_CODE, values);
    }

    /**
     * Fetch records that have <code>lg_city BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<MedicineOrderReceivePO> fetchRangeOfLgCity(String lowerInclusive, String upperInclusive) {
        return fetchRange(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_CITY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lg_city IN (values)</code>
     */
    public List<MedicineOrderReceivePO> fetchByLgCity(String... values) {
        return fetch(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_CITY, values);
    }

    /**
     * Fetch records that have <code>lg_city_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<MedicineOrderReceivePO> fetchRangeOfLgCityCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_CITY_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lg_city_code IN (values)</code>
     */
    public List<MedicineOrderReceivePO> fetchByLgCityCode(String... values) {
        return fetch(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_CITY_CODE, values);
    }

    /**
     * Fetch records that have <code>lg_area BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<MedicineOrderReceivePO> fetchRangeOfLgArea(String lowerInclusive, String upperInclusive) {
        return fetchRange(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_AREA, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lg_area IN (values)</code>
     */
    public List<MedicineOrderReceivePO> fetchByLgArea(String... values) {
        return fetch(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_AREA, values);
    }

    /**
     * Fetch records that have <code>lg_area_code BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<MedicineOrderReceivePO> fetchRangeOfLgAreaCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_AREA_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lg_area_code IN (values)</code>
     */
    public List<MedicineOrderReceivePO> fetchByLgAreaCode(String... values) {
        return fetch(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_AREA_CODE, values);
    }

    /**
     * Fetch records that have <code>lg_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<MedicineOrderReceivePO> fetchRangeOfLgName(String lowerInclusive, String upperInclusive) {
        return fetchRange(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lg_name IN (values)</code>
     */
    public List<MedicineOrderReceivePO> fetchByLgName(String... values) {
        return fetch(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_NAME, values);
    }

    /**
     * Fetch records that have <code>lg_phone BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<MedicineOrderReceivePO> fetchRangeOfLgPhone(String lowerInclusive, String upperInclusive) {
        return fetchRange(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_PHONE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lg_phone IN (values)</code>
     */
    public List<MedicineOrderReceivePO> fetchByLgPhone(String... values) {
        return fetch(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_PHONE, values);
    }

    /**
     * Fetch records that have <code>lg_address BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<MedicineOrderReceivePO> fetchRangeOfLgAddress(String lowerInclusive, String upperInclusive) {
        return fetchRange(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_ADDRESS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lg_address IN (values)</code>
     */
    public List<MedicineOrderReceivePO> fetchByLgAddress(String... values) {
        return fetch(MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_ADDRESS, values);
    }
        public List<MedicineOrderReceivePO> fetchById(Collection<Long> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.ID, value.toArray(new Long[value.size()]));
        }
        public List<MedicineOrderReceivePO> fetchByCreatedTime(Collection<LocalDateTime> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.CREATED_TIME, value.toArray(new LocalDateTime[value.size()]));
        }
        public List<MedicineOrderReceivePO> fetchByMedicineOrderId(Collection<Long> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.MEDICINE_ORDER_ID, value.toArray(new Long[value.size()]));
        }
        public List<MedicineOrderReceivePO> fetchByLgProvince(Collection<String> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_PROVINCE, value.toArray(new String[value.size()]));
        }
        public List<MedicineOrderReceivePO> fetchByLgProvinceCode(Collection<String> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_PROVINCE_CODE, value.toArray(new String[value.size()]));
        }
        public List<MedicineOrderReceivePO> fetchByLgCity(Collection<String> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_CITY, value.toArray(new String[value.size()]));
        }
        public List<MedicineOrderReceivePO> fetchByLgCityCode(Collection<String> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_CITY_CODE, value.toArray(new String[value.size()]));
        }
        public List<MedicineOrderReceivePO> fetchByLgArea(Collection<String> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_AREA, value.toArray(new String[value.size()]));
        }
        public List<MedicineOrderReceivePO> fetchByLgAreaCode(Collection<String> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_AREA_CODE, value.toArray(new String[value.size()]));
        }
        public List<MedicineOrderReceivePO> fetchByLgName(Collection<String> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_NAME, value.toArray(new String[value.size()]));
        }
        public List<MedicineOrderReceivePO> fetchByLgPhone(Collection<String> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_PHONE, value.toArray(new String[value.size()]));
        }
        public List<MedicineOrderReceivePO> fetchByLgAddress(Collection<String> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.MedicineOrderReceive.MEDICINE_ORDER_RECEIVE.LG_ADDRESS, value.toArray(new String[value.size()]));
        }
}
