/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.daos;


import cn.yxtreme.jooq.jooq.tables.MedicineOrderFlow;
import cn.yxtreme.jooq.jooq.tables.pojos.MedicineOrderFlowPO;
import cn.yxtreme.jooq.jooq.tables.records.MedicineOrderFlowRecord;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedicineOrderFlowDao extends DAOImpl<MedicineOrderFlowRecord, MedicineOrderFlowPO, Long> {

    /**
     * Create a new MedicineOrderFlowDao without any configuration
     */
    public MedicineOrderFlowDao() {
        super(MedicineOrderFlow.MEDICINE_ORDER_FLOW, MedicineOrderFlowPO.class);
    }

    /**
     * Create a new MedicineOrderFlowDao with an attached configuration
     */
    public MedicineOrderFlowDao(Configuration configuration) {
        super(MedicineOrderFlow.MEDICINE_ORDER_FLOW, MedicineOrderFlowPO.class, configuration);
    }

    @Override
    public Long getId(MedicineOrderFlowPO object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<MedicineOrderFlowPO> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(MedicineOrderFlow.MEDICINE_ORDER_FLOW.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<MedicineOrderFlowPO> fetchById(Long... values) {
        return fetch(MedicineOrderFlow.MEDICINE_ORDER_FLOW.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public MedicineOrderFlowPO fetchOneById(Long value) {
        return fetchOne(MedicineOrderFlow.MEDICINE_ORDER_FLOW.ID, value);
    }

    /**
     * Fetch records that have <code>created_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<MedicineOrderFlowPO> fetchRangeOfCreatedTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(MedicineOrderFlow.MEDICINE_ORDER_FLOW.CREATED_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_time IN (values)</code>
     */
    public List<MedicineOrderFlowPO> fetchByCreatedTime(LocalDateTime... values) {
        return fetch(MedicineOrderFlow.MEDICINE_ORDER_FLOW.CREATED_TIME, values);
    }

    /**
     * Fetch records that have <code>medicine_order_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<MedicineOrderFlowPO> fetchRangeOfMedicineOrderId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(MedicineOrderFlow.MEDICINE_ORDER_FLOW.MEDICINE_ORDER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>medicine_order_id IN (values)</code>
     */
    public List<MedicineOrderFlowPO> fetchByMedicineOrderId(Long... values) {
        return fetch(MedicineOrderFlow.MEDICINE_ORDER_FLOW.MEDICINE_ORDER_ID, values);
    }

    /**
     * Fetch records that have <code>order_status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<MedicineOrderFlowPO> fetchRangeOfOrderStatus(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(MedicineOrderFlow.MEDICINE_ORDER_FLOW.ORDER_STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>order_status IN (values)</code>
     */
    public List<MedicineOrderFlowPO> fetchByOrderStatus(Integer... values) {
        return fetch(MedicineOrderFlow.MEDICINE_ORDER_FLOW.ORDER_STATUS, values);
    }
        public List<MedicineOrderFlowPO> fetchById(Collection<Long> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.MedicineOrderFlow.MEDICINE_ORDER_FLOW.ID, value.toArray(new Long[value.size()]));
        }
        public List<MedicineOrderFlowPO> fetchByCreatedTime(Collection<LocalDateTime> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.MedicineOrderFlow.MEDICINE_ORDER_FLOW.CREATED_TIME, value.toArray(new LocalDateTime[value.size()]));
        }
        public List<MedicineOrderFlowPO> fetchByMedicineOrderId(Collection<Long> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.MedicineOrderFlow.MEDICINE_ORDER_FLOW.MEDICINE_ORDER_ID, value.toArray(new Long[value.size()]));
        }
        public List<MedicineOrderFlowPO> fetchByOrderStatus(Collection<Integer> value) {
                return fetch(cn.yxtreme.jooq.jooq.tables.MedicineOrderFlow.MEDICINE_ORDER_FLOW.ORDER_STATUS, value.toArray(new Integer[value.size()]));
        }
}
