/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.pojos;


import cn.yxtreme.jooq.model.BasePO;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;
import lombok.experimental.SuperBuilder;


/**
 * 中药表
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@SuperBuilder
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChineseMedicinePO extends BasePO implements Serializable {

    private static final long serialVersionUID = 1L;

        private String        herbName;
        private Long          skuId;
        private BigDecimal    settlementPrice;
        private LocalDateTime createdTime;
        private LocalDateTime updatedTime;
        private Boolean       deleted;
        private BigDecimal    sellPrice;
        private BigDecimal    referencePrice;
}
