/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.pojos;


import cn.yxtreme.jooq.model.BasePO;

import java.io.Serializable;
import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;
import lombok.experimental.SuperBuilder;

import org.jooq.JSON;


/**
 * This class is generated by jOOQ.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@SuperBuilder
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExpressDeliveryPO extends BasePO implements Serializable {

    private static final long serialVersionUID = 1L;

        private String        carrierCompany;
        private String        carrierOrderid;
        private LocalDateTime createdTime;
        private LocalDateTime updatedTime;
        private String        orderId;
        private JSON          deliverInfo;
        private Integer       thirdBusiness;
}
