/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.pojos;


import cn.yxtreme.jooq.model.BasePO;

import java.io.Serializable;
import java.time.OffsetDateTime;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;
import lombok.experimental.SuperBuilder;


/**
 * 接口调用记录表
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@SuperBuilder
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InterfaceRecordPO extends BasePO implements Serializable {

    private static final long serialVersionUID = 1L;

        private String         interfaceName;
        private String         request;
        private String         response;
        private OffsetDateTime createdAt;
}
