/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.pojos;


import cn.yxtreme.jooq.model.BasePO;

import java.io.Serializable;
import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;
import lombok.experimental.SuperBuilder;


/**
 * 订单表
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@SuperBuilder
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedicineOrderReceivePO extends BasePO implements Serializable {

    private static final long serialVersionUID = 1L;

        private LocalDateTime createdTime;
        private Long          medicineOrderId;
        private String        lgProvince;
        private String        lgProvinceCode;
        private String        lgCity;
        private String        lgCityCode;
        private String        lgArea;
        private String        lgAreaCode;
        private String        lgName;
        private String        lgPhone;
        private String        lgAddress;
}
