/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.pojos;


import cn.yxtreme.jooq.model.BasePO;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;
import lombok.experimental.SuperBuilder;


/**
 * 开药表
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@SuperBuilder
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedicineV2PO extends BasePO implements Serializable {

    private static final long serialVersionUID = 1L;

        private Long          consultOrderId;
        private LocalDateTime createdTime;
        private Long          patientId;
        private Long          providerId;
        private Long          assistantId;
        private Long          imSessionId;
        private Long          leaderId;
        private String        ptNo;
        private LocalDate     birthday;
        private Integer       sex;
        private String        departmentName;
        private String        idNo;
        private String        complaintContent;
        private String        diseaesName;
        private String        shopId;
        private String        pregnant;
        private String        allergies;
        private String        contraindications;
        private BigDecimal    weight;
        private Long          medicineOrderId;
        private Boolean       isUsable;
        private Integer       idCardType;
        private String        comments;
        private Boolean       prescription;
        private Boolean       forward;
        private Long          forwardUserId;
        private String        forwardDepartment;
        private String        doctorName;
        private String        forwardUserName;
        private String        prescriptionBase64;
        private Integer       shopType;
}
