/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.pojos;


import cn.yxtreme.jooq.model.BasePO;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;
import lombok.experimental.SuperBuilder;


/**
 * 订单表
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@SuperBuilder
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MedicineOrderPO extends BasePO implements Serializable {

    private static final long serialVersionUID = 1L;

        private LocalDateTime createdTime;
        private LocalDateTime updatedTime;
        private Integer       orderStatus;
        private String        thirdOrderId;
        private Integer       thirdBusiness;
        private Long          totalPrice;
        private Long          deductionAmmount;
        private Long          deliverPay;
        private Long          hadPay;
        private BigDecimal    latitude;
        private BigDecimal    longitude;
        private Boolean       rights;
        private String        rightsUseId;
        private Boolean       rightsCommit;
        private Long          rightsId;
        private Long          deliverDiscount;
        private String        abandonedReason;
        private Long          totalOriginalPrice;
        private String        orderNo;
}
