/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.pojos;


import cn.yxtreme.jooq.model.BasePO;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;
import lombok.experimental.SuperBuilder;


/**
 * 标准方
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@SuperBuilder
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NormalMedicationPO extends BasePO implements Serializable {

    private static final long serialVersionUID = 1L;

        private String        name;
        private Long          version;
        private Long          dosage;
        private Long          rate;
        private Long          processingMethods;
        private Long          usage;
        private Long          usageUnit;
        private BigDecimal    settlementPrice;
        private BigDecimal    sellPrice;
        private String        remark;
        private Long          createdUserId;
        private Long          updatedUserId;
        private String        createdUser;
        private String        updatedUser;
        private LocalDateTime createdAt;
        private LocalDateTime updatedAt;
        private Integer       status;
}
