/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.pojos;


import cn.yxtreme.jooq.model.BasePO;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;
import lombok.experimental.SuperBuilder;


/**
 * 订单表
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@SuperBuilder
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderPO extends BasePO implements Serializable {

    private static final long serialVersionUID = 1L;

        private String        orderNo;
        private Long          createdUser;
        private Long          updatedUser;
        private LocalDateTime createdTime;
        private LocalDateTime updatedTime;
        private Integer       orderStatus;
        private String        ddOrderNo;
        private Long          totalPrice;
        private Long          totalPay;
        private Long          deductionAmmount;
        private Long          deliverPay;
        private LocalDateTime payTime;
        private LocalDateTime initTime;
        private LocalDateTime commitTime;
        private LocalDateTime cancelTime;
        private LocalDateTime refundTime;
        private Boolean       prescription;
        private Long          hadPay;
        private Long          mobile;
        private String        city;
        private Long          patientId;
        private Long          leaderId;
        private Long          providerId;
        private BigDecimal    latitude;
        private BigDecimal    longitude;
        private String        address;
        private Boolean       right;
        private String        doctorName;
        private Long          rightUseId;
        private LocalDateTime deliveredTime;
        private Boolean       rightCommit;
        private Long          rightsId;
        private Integer       shopType;
        private String        logistic;
        private String        area;
        private String        lgAddress;
        private String        lgPhone;
        private String        lgProvince;
        private String        lgCity;
        private String        lgArea;
        private String        lgName;
        private String        abandonedReason;
}
