/*
 * This file is generated by jOOQ.
 */
package cn.yxtreme.jooq.jooq.tables.pojos;


import cn.yxtreme.jooq.model.BasePO;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;
import lombok.experimental.SuperBuilder;


/**
 * 订单表
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@SuperBuilder
@Accessors(chain = true)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderV2PO extends BasePO implements Serializable {

    private static final long serialVersionUID = 1L;

        private LocalDateTime createdTime;
        private LocalDateTime updatedTime;
        private Integer       orderStatus;
        private String        thirdOrderId;
        private Integer       thirdBusiness;
        private Long          totalPrice;
        private Long          totalPay;
        private Long          deductionAmmount;
        private Long          deliverPay;
        private LocalDateTime payTime;
        private LocalDateTime initTime;
        private LocalDateTime commitTime;
        private LocalDateTime cancelTime;
        private LocalDateTime refundTime;
        private Long          hadPay;
        private BigDecimal    latitude;
        private BigDecimal    longitude;
        private Boolean       rights;
        private Long          rightsUseId;
        private LocalDateTime deliveredTime;
        private Boolean       rightsCommit;
        private Long          rightsId;
        private String        lgProvince;
        private String        lgProvinceCode;
        private String        lgCity;
        private String        lgCityCode;
        private String        lgArea;
        private String        lgAreaCode;
        private String        lgName;
        private String        lgPhone;
        private String        lgAddress;
}
